In [1]:
import sys
import os

# 1. Get the path to the parent directory (project_root)
parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))

# 2. Add the parent directory to Python's system path
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

# 3. Import your functions
from src.preprocess_01 import print_hello
print_hello()

Hello, import successful!

In [2]:
import pandas as pd
import numpy as np

clinical_hnsc_pd = pd.read_csv('../data/raw/TCGA-HNSC.clinical.tsv', sep='\t')
methylation_hnsc_pd = pd.read_csv('../data/raw/TCGA-HNSC.methylation450.tsv', sep='\t')

In [3]:
methylation_hnsc_pd

,Composite Element REF,TCGA-F7-A61V-01A,TCGA-CV-7407-01A,TCGA-UF-A7JO-01A,TCGA-CV-6948-01A,TCGA-BB-7864-01A,TCGA-DQ-5629-01A,TCGA-CV-5436-01A,TCGA-P3-A6T6-01A,TCGA-CQ-7071-01A,...,TCGA-CV-5978-11A,TCGA-CV-A6JE-01A,TCGA-C9-A480-01A,TCGA-CN-A640-01A,TCGA-CR-7399-01A,TCGA-CV-7432-01A,TCGA-CR-6471-01A,TCGA-MT-A67A-01A,TCGA-H7-7774-01A,TCGA-CV-7415-01A
0,cg00000029,0.169494,0.271910,0.417004,0.128467,0.171842,0.210423,0.445202,0.147907,0.287879,...,0.458812,0.261876,0.438269,0.616487,0.428766,0.485641,0.393504,0.606525,0.561132,0.162578
1,cg00000108,0.969504,0.968134,0.955937,0.968904,0.958299,0.954517,0.953881,0.966916,0.977288,...,0.974592,0.944286,0.967228,0.956722,0.967467,0.954409,0.957079,0.958249,0.973065,0.939583
2,cg00000109,0.901731,0.955765,0.921865,0.910797,0.945290,0.886882,0.922131,0.947652,0.927461,...,0.907550,0.924602,0.925155,0.935575,0.941800,0.937185,0.929260,0.923488,0.924097,0.943951
3,cg00000165,0.575925,0.643235,0.488987,0.860205,0.723734,0.869253,0.669761,0.854011,0.512599,...,0.187564,0.234833,0.686566,0.440520,0.784651,0.734791,0.705929,0.499184,0.692248,0.763323
4,cg00000236,0.884583,0.934308,0.906538,0.921293,0.904258,0.843967,0.921914,0.904108,0.935241,...,0.901018,0.930109,0.914718,0.896995,0.911715,0.917020,0.926273,0.919832,0.930900,0.922248
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486422,rs9363764,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486423,rs939290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486424,rs951295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486425,rs966367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486426,rs9839873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
clinical_hnsc_pd

,sample,id,disease_type,case_id,submitter_id,primary_site,cigarettes_per_day.exposures,alcohol_history.exposures,years_smoked.exposures,pack_years_smoked.exposures,...,is_ffpe.samples,tissue_type.samples,preservation_method.samples,composition.samples,days_to_collection.samples,initial_weight.samples,intermediate_dimension.samples,pathology_report_uuid.samples,shortest_dimension.samples,longest_dimension.samples
0,TCGA-BB-4227-01A,b8ac8500-abcd-40c4-9c24-7af557fd260a,Squamous Cell Neoplasms,b8ac8500-abcd-40c4-9c24-7af557fd260a,TCGA-BB-4227,Hypopharynx,1.369863,Yes,NaN,25.0,...,False,Tumor,Unknown,Not Reported,NaN,NaN,0.6,97efcea3-fa0b-4fe6-9224-094354eb6351,0.2,0.7
1,TCGA-CR-6478-01A,467d5c94-1e67-4454-9e9c-9dffaa643032,Squamous Cell Neoplasms,467d5c94-1e67-4454-9e9c-9dffaa643032,TCGA-CR-6478,Tonsil,NaN,Yes,35.0,NaN,...,False,Tumor,Unknown,Not Reported,NaN,NaN,NaN,3ec65b65-8bd9-486f-8866-3de22eff8865,NaN,NaN
2,TCGA-BB-4228-01A,cac30b32-03ef-4ecb-88d8-d5577ab6b2a6,Squamous Cell Neoplasms,cac30b32-03ef-4ecb-88d8-d5577ab6b2a6,TCGA-BB-4228,Base of tongue,5.616438,Yes,NaN,102.5,...,False,Tumor,Unknown,Not Reported,NaN,NaN,0.7,39956346-2d64-4d6a-8b64-a0e8c2406515,0.2,0.8
3,TCGA-BA-4075-01A,6fa62461-e721-415a-8b0f-363b84292b82,Squamous Cell Neoplasms,6fa62461-e721-415a-8b0f-363b84292b82,TCGA-BA-4075,Other and unspecified parts of tongue,1.643836,Yes,NaN,30.0,...,False,Tumor,Unknown,Not Reported,NaN,NaN,0.7,d71f3395-4b46-458a-8a51-0130aa40ffad,0.3,1.0
4,TCGA-CX-7082-01A,47d1fcaf-3c01-43ba-9a21-0870b4ea2976,Squamous Cell Neoplasms,47d1fcaf-3c01-43ba-9a21-0870b4ea2976,TCGA-CX-7082,"Other and ill-defined sites in lip, oral cavit...",2.739726,Yes,NaN,50.0,...,False,Tumor,Unknown,Not Reported,NaN,NaN,0.2,872be720-140a-4152-84ce-184d1a2cdfe7,0.2,0.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599,TCGA-CV-7242-11A,4b4247e2-4446-44f5-8573-4cea8bf69f8e,Squamous Cell Neoplasms,4b4247e2-4446-44f5-8573-4cea8bf69f8e,TCGA-CV-7242,Larynx,2.191781,Yes,NaN,40.0,...,False,Normal,Unknown,Not Reported,NaN,NaN,1.0,NaN,1.0,1.2
600,TCGA-TN-A7HL-01A,4b50aea4-4ad1-4bf6-9cf1-984c28a99c84,Squamous Cell Neoplasms,4b50aea4-4ad1-4bf6-9cf1-984c28a99c84,TCGA-TN-A7HL,Hypopharynx,0.547945,Yes,20.0,10.0,...,False,Tumor,OCT,Not Reported,45.0,230.0,NaN,BED776A5-936A-468C-B469-EF9FB12109D1,NaN,NaN
601,TCGA-CV-A6JZ-01A,4cacff9d-cc50-43a5-a227-16923ada7467,Squamous Cell Neoplasms,4cacff9d-cc50-43a5-a227-16923ada7467,TCGA-CV-A6JZ,Other and unspecified parts of mouth,2.904110,Yes,NaN,53.0,...,False,Tumor,Unknown,Not Reported,564.0,30.0,NaN,8FFB88B7-4E49-4455-98D1-38013FF7C0ED,NaN,NaN
602,TCGA-CV-5444-11A,4eacd173-025a-442b-8bce-890ccfdca586,Squamous Cell Neoplasms,4eacd173-025a-442b-8bce-890ccfdca586,TCGA-CV-5444,Larynx,NaN,Yes,NaN,NaN,...,False,Normal,Unknown,Not Reported,NaN,NaN,NaN,NaN,NaN,NaN
603,TCGA-CV-5444-01A,4eacd173-025a-442b-8bce-890ccfdca586,Squamous Cell Neoplasms,4eacd173-025a-442b-8bce-890ccfdca586,TCGA-CV-5444,Larynx,NaN,Yes,NaN,NaN,...,False,Tumor,Unknown,Not Reported,NaN,NaN,0.4,7d30150f-cadd-48cf-8146-387b40529c56,0.3,0.5

In [5]:
#transpose the methylation dataframe

methylation_hnsc_pd.set_index('Composite Element REF', inplace=True)
methylation_hnsc_pd_old = methylation_hnsc_pd.transpose()
methylation_hnsc_pd_old

Composite Element REF,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs7746156,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873
TCGA-F7-A61V-01A,0.169494,0.969504,0.901731,0.575925,0.884583,0.664639,0.443790,0.527111,0.201535,0.016330,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCGA-CV-7407-01A,0.271910,0.968134,0.955765,0.643235,0.934308,0.722358,0.772394,0.736274,0.313491,0.014606,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCGA-UF-A7JO-01A,0.417004,0.955937,0.921865,0.488987,0.906538,0.703528,0.757155,0.564353,0.325092,0.015789,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCGA-CV-6948-01A,0.128467,0.968904,0.910797,0.860205,0.921293,0.743871,0.547383,0.674936,0.230438,0.012691,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCGA-BB-7864-01A,0.171842,0.958299,0.945290,0.723734,0.904258,0.783855,0.461953,0.285278,0.221449,0.013150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-CV-7432-01A,0.485641,0.954409,0.937185,0.734791,0.917020,0.782199,0.736587,0.466652,0.435981,0.015868,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCGA-CR-6471-01A,0.393504,0.957079,0.929260,0.705929,0.926273,0.786158,0.733265,0.559355,0.275917,0.017546,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCGA-MT-A67A-01A,0.606525,0.958249,0.923488,0.499184,0.919832,0.811452,0.665014,0.574861,0.346464,0.012115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCGA-H7-7774-01A,0.561132,0.973065,0.924097,0.692248,0.930900,0.760912,0.749997,0.654586,0.266455,0.015712,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCGA-CV-7415-01A,0.162578,0.939583,0.943951,0.763323,0.922248,NaN,0.740405,0.569332,0.249119,0.013830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
import pandas as pd
from sklearn.impute import SimpleImputer

# --- STEP 1: Drop probes with too many NaNs ---
# Calculate the threshold for 10% missingness
# (e.g., if you have 370 tumor samples, keep probes that have at least 333 valid values)
threshold = int(methylation_hnsc_pd_old.shape[0] * 0.90)

# Drop columns (probes) that do not meet the threshold
methylation_hnsc_pd = methylation_hnsc_pd_old.dropna(axis=1, thresh=threshold)

print(f"Original probes: {methylation_hnsc_pd_old.shape[1]}")
print(f"Probes after dropping bad ones: {methylation_hnsc_pd.shape[1]}")

Original probes: 486427
Probes after dropping bad ones: 406061

In [7]:
methylation_hnsc_pd

Composite Element REF,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000292,cg00000321,cg00000363,cg00000622,cg00000658,...,ctl_70664314,ctl_70700334,ctl_71670310,ctl_71678368,ctl_71718498,ctl_72748406,ctl_73635489,ctl_73784382,ctl_73794434,ctl_74666473
TCGA-F7-A61V-01A,0.169494,0.969504,0.901731,0.575925,0.884583,0.443790,0.527111,0.201535,0.016330,0.899096,...,0.024935,0.074955,0.934347,0.074081,0.109095,0.123795,0.055536,0.893430,0.924984,0.958676
TCGA-CV-7407-01A,0.271910,0.968134,0.955765,0.643235,0.934308,0.772394,0.736274,0.313491,0.014606,0.832098,...,0.097556,0.054384,0.965121,0.051201,0.218709,0.076075,0.070833,0.929056,0.972468,0.952202
TCGA-UF-A7JO-01A,0.417004,0.955937,0.921865,0.488987,0.906538,0.757155,0.564353,0.325092,0.015789,0.843975,...,0.028748,0.091012,0.960164,0.055483,0.166570,0.120988,0.063425,0.931578,0.951702,0.964257
TCGA-CV-6948-01A,0.128467,0.968904,0.910797,0.860205,0.921293,0.547383,0.674936,0.230438,0.012691,0.889466,...,0.039361,0.055663,0.960194,0.065371,0.177939,0.097036,0.088908,0.936490,0.955121,0.957882
TCGA-BB-7864-01A,0.171842,0.958299,0.945290,0.723734,0.904258,0.461953,0.285278,0.221449,0.013150,0.889051,...,0.023655,0.063635,0.968602,0.053799,0.178144,0.092968,0.052888,0.955130,0.970614,0.968689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-CV-7432-01A,0.485641,0.954409,0.937185,0.734791,0.917020,0.736587,0.466652,0.435981,0.015868,0.806900,...,0.129434,0.072841,0.966988,0.078038,0.219387,0.115900,0.061564,0.921702,0.956045,0.957312
TCGA-CR-6471-01A,0.393504,0.957079,0.929260,0.705929,0.926273,0.733265,0.559355,0.275917,0.017546,0.878021,...,0.070154,0.101726,0.949204,0.053345,0.188774,0.124597,0.066099,0.938521,0.953174,0.978739
TCGA-MT-A67A-01A,0.606525,0.958249,0.923488,0.499184,0.919832,0.665014,0.574861,0.346464,0.012115,0.844069,...,0.018265,0.086160,0.967759,0.055477,0.086231,0.102222,0.062569,0.944587,0.963469,0.959490
TCGA-H7-7774-01A,0.561132,0.973065,0.924097,0.692248,0.930900,0.749997,0.654586,0.266455,0.015712,0.873654,...,0.080932,0.058969,0.967671,0.056863,0.184611,0.072771,0.062440,0.944116,0.960702,0.952825
TCGA-CV-7415-01A,0.162578,0.939583,0.943951,0.763323,0.922248,0.740405,0.569332,0.249119,0.013830,0.877001,...,0.088900,0.074435,0.962625,0.096838,0.202180,0.092403,0.065178,0.941396,0.963867,0.959952

In [8]:
print(f"Total NaNs remaining: {methylation_hnsc_pd.isna().sum().sum()}")

Total NaNs remaining: 717988

In [9]:
# --- STEP 2: Impute remaining NaNs ---
# Initialize the imputer to fill NaNs with the median value of each column
imputer = SimpleImputer(strategy='median')

# Fit and transform the data (Note: this returns a numpy array)
methylation_imputed_array = imputer.fit_transform(methylation_hnsc_pd)

# Convert back to a pandas DataFrame to keep your Patient IDs and Probe IDs safe
methylation_hnsc_pd = pd.DataFrame(
    methylation_imputed_array,
    index=methylation_hnsc_pd.index,      # Patient IDs
    columns=methylation_hnsc_pd.columns   # CpG Probe IDs
)

print(f"Total NaNs remaining: {methylation_hnsc_pd.isna().sum().sum()}")

Total NaNs remaining: 0

In [10]:
methylation_hnsc_pd

Composite Element REF,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000292,cg00000321,cg00000363,cg00000622,cg00000658,...,ctl_70664314,ctl_70700334,ctl_71670310,ctl_71678368,ctl_71718498,ctl_72748406,ctl_73635489,ctl_73784382,ctl_73794434,ctl_74666473
TCGA-F7-A61V-01A,0.169494,0.969504,0.901731,0.575925,0.884583,0.443790,0.527111,0.201535,0.016330,0.899096,...,0.024935,0.074955,0.934347,0.074081,0.109095,0.123795,0.055536,0.893430,0.924984,0.958676
TCGA-CV-7407-01A,0.271910,0.968134,0.955765,0.643235,0.934308,0.772394,0.736274,0.313491,0.014606,0.832098,...,0.097556,0.054384,0.965121,0.051201,0.218709,0.076075,0.070833,0.929056,0.972468,0.952202
TCGA-UF-A7JO-01A,0.417004,0.955937,0.921865,0.488987,0.906538,0.757155,0.564353,0.325092,0.015789,0.843975,...,0.028748,0.091012,0.960164,0.055483,0.166570,0.120988,0.063425,0.931578,0.951702,0.964257
TCGA-CV-6948-01A,0.128467,0.968904,0.910797,0.860205,0.921293,0.547383,0.674936,0.230438,0.012691,0.889466,...,0.039361,0.055663,0.960194,0.065371,0.177939,0.097036,0.088908,0.936490,0.955121,0.957882
TCGA-BB-7864-01A,0.171842,0.958299,0.945290,0.723734,0.904258,0.461953,0.285278,0.221449,0.013150,0.889051,...,0.023655,0.063635,0.968602,0.053799,0.178144,0.092968,0.052888,0.955130,0.970614,0.968689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-CV-7432-01A,0.485641,0.954409,0.937185,0.734791,0.917020,0.736587,0.466652,0.435981,0.015868,0.806900,...,0.129434,0.072841,0.966988,0.078038,0.219387,0.115900,0.061564,0.921702,0.956045,0.957312
TCGA-CR-6471-01A,0.393504,0.957079,0.929260,0.705929,0.926273,0.733265,0.559355,0.275917,0.017546,0.878021,...,0.070154,0.101726,0.949204,0.053345,0.188774,0.124597,0.066099,0.938521,0.953174,0.978739
TCGA-MT-A67A-01A,0.606525,0.958249,0.923488,0.499184,0.919832,0.665014,0.574861,0.346464,0.012115,0.844069,...,0.018265,0.086160,0.967759,0.055477,0.086231,0.102222,0.062569,0.944587,0.963469,0.959490
TCGA-H7-7774-01A,0.561132,0.973065,0.924097,0.692248,0.930900,0.749997,0.654586,0.266455,0.015712,0.873654,...,0.080932,0.058969,0.967671,0.056863,0.184611,0.072771,0.062440,0.944116,0.960702,0.952825
TCGA-CV-7415-01A,0.162578,0.939583,0.943951,0.763323,0.922248,0.740405,0.569332,0.249119,0.013830,0.877001,...,0.088900,0.074435,0.962625,0.096838,0.202180,0.092403,0.065178,0.941396,0.963867,0.959952

In [11]:
clinical_hnsc_pd.columns

Index(['sample', 'id', 'disease_type', 'case_id', 'submitter_id',
       'primary_site', 'cigarettes_per_day.exposures',
       'alcohol_history.exposures', 'years_smoked.exposures',
       'pack_years_smoked.exposures', 'race.demographic', 'gender.demographic',
       'ethnicity.demographic', 'vital_status.demographic',
       'age_at_index.demographic', 'days_to_birth.demographic',
       'year_of_birth.demographic', 'year_of_death.demographic',
       'primary_site.project', 'project_id.project', 'disease_type.project',
       'name.project', 'name.program.project',
       'tissue_source_site_id.tissue_source_site', 'code.tissue_source_site',
       'name.tissue_source_site', 'project.tissue_source_site',
       'bcr_id.tissue_source_site', 'days_to_death.demographic',
       'entity_submitter_id.annotations', 'notes.annotations',
       'submitter_id.annotations', 'classification.annotations',
       'entity_id.annotations', 'created_datetime.annotations',
       'annotation_id.annotations', 'entity_type.annotations',
       'updated_datetime.annotations', 'case_id.annotations',
       'state.annotations', 'category.annotations', 'status.annotations',
       'case_submitter_id.annotations', 'synchronous_malignancy.diagnoses',
       'ajcc_pathologic_stage.diagnoses', 'days_to_diagnosis.diagnoses',
       'last_known_disease_status.diagnoses',
       'tissue_or_organ_of_origin.diagnoses',
       'days_to_last_follow_up.diagnoses', 'age_at_diagnosis.diagnoses',
       'primary_diagnosis.diagnoses', 'ajcc_clinical_stage.diagnoses',
       'prior_malignancy.diagnoses', 'year_of_diagnosis.diagnoses',
       'prior_treatment.diagnoses', 'ajcc_staging_system_edition.diagnoses',
       'ajcc_pathologic_t.diagnoses', 'morphology.diagnoses',
       'ajcc_clinical_m.diagnoses', 'ajcc_pathologic_n.diagnoses',
       'ajcc_clinical_n.diagnoses', 'ajcc_clinical_t.diagnoses',
       'classification_of_tumor.diagnoses', 'icd_10_code.diagnoses',
       'site_of_resection_or_biopsy.diagnoses', 'tumor_grade.diagnoses',
       'progression_or_recurrence.diagnoses', 'ajcc_pathologic_m.diagnoses',
       'age_at_earliest_diagnosis.diagnoses.xena_derived',
       'age_at_earliest_diagnosis_in_years.diagnoses.xena_derived',
       'treatment_id.treatments.diagnoses',
       'submitter_id.treatments.diagnoses',
       'treatment_type.treatments.diagnoses',
       'treatment_or_therapy.treatments.diagnoses',
       'created_datetime.treatments.diagnoses',
       'updated_datetime.treatments.diagnoses', 'state.treatments.diagnoses',
       'sample_type_id.samples', 'tumor_descriptor.samples',
       'sample_id.samples', 'sample_type.samples', 'oct_embedded.samples',
       'specimen_type.samples', 'is_ffpe.samples', 'tissue_type.samples',
       'preservation_method.samples', 'composition.samples',
       'days_to_collection.samples', 'initial_weight.samples',
       'intermediate_dimension.samples', 'pathology_report_uuid.samples',
       'shortest_dimension.samples', 'longest_dimension.samples'],
      dtype='object')

In [12]:
columns_to_keep = [
    # --- Identifiers & Subsetting ---
    'sample',                                  # Keep as index to match methylation matrix
    'sample_type.samples',                     # Essential: For subsetting (Tumor vs Normal)
    'tissue_type.samples',                     # Alternative/backup for subsetting
    
    # --- Disease Scope (Useful if merging with other TCGA cohorts later) ---
    'disease_type',                            # e.g., Liver Hepatocellular Carcinoma
    'primary_site',                            # e.g., Liver
    
    # --- Clinical & Progression ---
    'tumor_grade.diagnoses',                   # Highly correlated with methylation changes
    'ajcc_pathologic_stage.diagnoses',         # Overall disease stage
    
    # --- Risk Factors & Demographics ---
    'alcohol_history.exposures',               # Major epigenetic driver in HNSC
    'gender.demographic',                      # Strong bias in HNSC / Check for sex chromosome filtering
    'race.demographic',                        # Check for disparities/patterns
    'vital_status.demographic',                # Survival correlation
    
    # --- Technical / Batch Effect Checking ---
    'tissue_source_site_id.tissue_source_site',# ID of the collection hospital
    'name.tissue_source_site',                  # Name of the collection hospital
    
    'cigarettes_per_day.exposures',               # Another major epigenetic driver in HNSC
    'pack_years_smoked.exposures',               # Cumulative smoking exposure
    'age_at_index.demographic',                      # Age at diagnosis (important for methylation patterns)
    'tissue_or_organ_of_origin.diagnoses',                   # Tissue of origin (e.g., Oral Cavity, Larynx)
    'primary_diagnosis.diagnoses',                   # Primary diagnosis (e.g., Squamous Cell Carcinoma)
]

# Filter your phenotype dataframe
clinical_hnsc_pd_filtered = clinical_hnsc_pd[columns_to_keep]
clinical_hnsc_pd_filtered

,sample,sample_type.samples,tissue_type.samples,disease_type,primary_site,tumor_grade.diagnoses,ajcc_pathologic_stage.diagnoses,alcohol_history.exposures,gender.demographic,race.demographic,vital_status.demographic,tissue_source_site_id.tissue_source_site,name.tissue_source_site,cigarettes_per_day.exposures,pack_years_smoked.exposures,age_at_index.demographic,tissue_or_organ_of_origin.diagnoses,primary_diagnosis.diagnoses
0,TCGA-BB-4227-01A,Primary Tumor,Tumor,Squamous Cell Neoplasms,Hypopharynx,Not Reported,Stage IVA,Yes,male,white,Alive,a7da35ad-149e-5014-932b-37f188536bf8,Johns Hopkins,1.369863,25.0,66.0,"Hypopharynx, NOS","Squamous cell carcinoma, NOS"
1,TCGA-CR-6478-01A,Primary Tumor,Tumor,Squamous Cell Neoplasms,Tonsil,Not Reported,NaN,Yes,female,white,Dead,041ae4a7-3724-5587-82a9-8e09d3ee3cb8,Vanderbilt University,NaN,NaN,66.0,"Tonsil, NOS","Squamous cell carcinoma, NOS"
2,TCGA-BB-4228-01A,Primary Tumor,Tumor,Squamous Cell Neoplasms,Base of tongue,Not Reported,Stage III,Yes,male,white,Alive,a7da35ad-149e-5014-932b-37f188536bf8,Johns Hopkins,5.616438,102.5,50.0,"Base of tongue, NOS","Squamous cell carcinoma, NOS"
3,TCGA-BA-4075-01A,Primary Tumor,Tumor,Squamous Cell Neoplasms,Other and unspecified parts of tongue,Not Reported,Stage III,Yes,male,black or african american,Dead,278e36e9-7faf-5043-ba90-2a4145ad0226,UNC,1.643836,30.0,49.0,"Tongue, NOS","Squamous cell carcinoma, NOS"
4,TCGA-CX-7082-01A,Primary Tumor,Tumor,Squamous Cell Neoplasms,"Other and ill-defined sites in lip, oral cavit...",Not Reported,Stage IVA,Yes,male,white,Dead,5184bb4b-3075-56fb-886f-7895a42e156b,Medical College of Georgia,2.739726,50.0,82.0,"Overlapping lesion of lip, oral cavity and pha...","Squamous cell carcinoma, NOS"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599,TCGA-CV-7242-11A,Solid Tissue Normal,Normal,Squamous Cell Neoplasms,Larynx,Not Reported,Stage II,Yes,female,white,Alive,e0529816-35d4-5963-93c3-72c127e4e372,MD Anderson Cancer Center,2.191781,40.0,60.0,"Larynx, NOS","Squamous cell carcinoma, NOS"
600,TCGA-TN-A7HL-01A,Primary Tumor,Tumor,Squamous Cell Neoplasms,Hypopharynx,Not Reported,Stage IVA,Yes,male,white,Alive,0880c76d-8168-580c-82c0-aeb6ba104840,Ohio State University,0.547945,10.0,59.0,"Hypopharynx, NOS","Squamous cell carcinoma, NOS"
601,TCGA-CV-A6JZ-01A,Primary Tumor,Tumor,Squamous Cell Neoplasms,Other and unspecified parts of mouth,Not Reported,Stage II,Yes,male,white,Alive,e0529816-35d4-5963-93c3-72c127e4e372,MD Anderson Cancer Center,2.904110,53.0,68.0,"Mouth, NOS","Squamous cell carcinoma, NOS"
602,TCGA-CV-5444-11A,Solid Tissue Normal,Normal,Squamous Cell Neoplasms,Larynx,Not Reported,Stage IVA,Yes,male,black or african american,Alive,e0529816-35d4-5963-93c3-72c127e4e372,MD Anderson Cancer Center,NaN,NaN,64.0,"Larynx, NOS","Squamous cell carcinoma, NOS"
603,TCGA-CV-5444-01A,Primary Tumor,Tumor,Squamous Cell Neoplasms,Larynx,Not Reported,Stage IVA,Yes,male,black or african american,Alive,e0529816-35d4-5963-93c3-72c127e4e372,MD Anderson Cancer Center,NaN,NaN,64.0,"Larynx, NOS","Squamous cell carcinoma, NOS"

In [13]:
# Shows the count of unique classes per column across the whole dataset
unique_counts = clinical_hnsc_pd_filtered.nunique()
print(unique_counts)

sample                                      604
sample_type.samples                           3
tissue_type.samples                           2
disease_type                                  1
primary_site                                 13
tumor_grade.diagnoses                         1
ajcc_pathologic_stage.diagnoses               6
alcohol_history.exposures                     3
gender.demographic                            2
race.demographic                              5
vital_status.demographic                      2
tissue_source_site_id.tissue_source_site     28
name.tissue_source_site                      28
cigarettes_per_day.exposures                 87
pack_years_smoked.exposures                  87
age_at_index.demographic                     60
tissue_or_organ_of_origin.diagnoses          24
primary_diagnosis.diagnoses                   5
dtype: int64

In [14]:
for col in clinical_hnsc_pd_filtered.columns:
    print(f"--- {col} ---")
    print(clinical_hnsc_pd_filtered[col].value_counts())
    print("\n")

--- sample ---
sample
TCGA-BB-4227-01A    1
TCGA-CV-7097-11A    1
TCGA-CR-6474-01A    1
TCGA-CV-7407-01A    1
TCGA-CQ-5330-01A    1
                   ..
TCGA-CQ-5332-01A    1
TCGA-BB-7861-01A    1
TCGA-D6-A6ES-01A    1
TCGA-BA-5556-01A    1
TCGA-CV-5444-01A    1
Name: count, Length: 604, dtype: int64


--- sample_type.samples ---
sample_type.samples
Primary Tumor          528
Solid Tissue Normal     74
Metastatic               2
Name: count, dtype: int64


--- tissue_type.samples ---
tissue_type.samples
Tumor     530
Normal     74
Name: count, dtype: int64


--- disease_type ---
disease_type
Squamous Cell Neoplasms    604
Name: count, dtype: int64


--- primary_site ---
primary_site
Other and unspecified parts of tongue                                   158
Larynx                                                                  140
Other and ill-defined sites in lip, oral cavity and pharynx              86
Floor of mouth                                                           62
Tonsil                                                                   47
Other and unspecified parts of mouth                                     44
Base of tongue                                                           27
Gum                                                                      11
Oropharynx                                                               10
Hypopharynx                                                               9
Palate                                                                    6
Lip                                                                       3
Bones, joints and articular cartilage of other and unspecified sites      1
Name: count, dtype: int64


--- tumor_grade.diagnoses ---
tumor_grade.diagnoses
Not Reported    604
Name: count, dtype: int64


--- ajcc_pathologic_stage.diagnoses ---
ajcc_pathologic_stage.diagnoses
Stage IVA    297
Stage III     96
Stage II      92
Stage I       29
Stage IVB     13
Stage IVC      1
Name: count, dtype: int64


--- alcohol_history.exposures ---
alcohol_history.exposures
Yes             399
No              191
Not Reported     14
Name: count, dtype: int64


--- gender.demographic ---
gender.demographic
male      440
female    164
Name: count, dtype: int64


--- race.demographic ---
race.demographic
white                               517
black or african american            56
not reported                         17
asian                                12
american indian or alaska native      2
Name: count, dtype: int64


--- vital_status.demographic ---
vital_status.demographic
Alive    331
Dead     273
Name: count, dtype: int64


--- tissue_source_site_id.tissue_source_site ---
tissue_source_site_id.tissue_source_site
e0529816-35d4-5963-93c3-72c127e4e372    203
e7f917f5-0bf7-524d-ba0d-c63b2240f04f     74
041ae4a7-3724-5587-82a9-8e09d3ee3cb8     54
b0c6de27-ffe0-5559-aa84-75a50eafdcd8     40
278e36e9-7faf-5043-ba90-2a4145ad0226     36
a7da35ad-149e-5014-932b-37f188536bf8     21
d47f66d9-bb92-556e-bb55-2f55f2f790dd     20
9ab83cd0-80e6-5853-8125-00a9a2a14965     19
01171aea-21ea-5da5-a729-f89154406e6f     18
0728db48-1343-5881-983e-fafd4e859f55     17
8f861c09-3b25-56dd-9582-e1b4d4d7739a     15
f1d310ba-b465-5d9a-a307-5e88e1040004     14
2083a3b2-a5c3-50e2-ac10-10de2451dbf1     13
9ead299b-307f-5408-aab2-da3801ef585d     13
e846d7bf-7649-577a-9fd3-9472b777f26d      8
5b9b443e-2c12-5810-b80f-492d01865b5a      7
5184bb4b-3075-56fb-886f-7895a42e156b      5
07e0e1ea-af09-517f-91be-4535cbb198f2      5
135afda5-876f-5672-92a9-e3c8eea61a5c      4
d5f243ad-2ab4-5967-9b9b-13f0b7ddd842      3
0880c76d-8168-580c-82c0-aeb6ba104840      3
7224663d-930a-5e5c-afcb-a6920fdc51ee      3
67c058f1-edd1-5c10-8e32-f4249f971735      2
4ba57422-7a2b-5e8b-a4b3-e0f14617ab7c      2
248a7e4b-d8e9-58be-86bf-18cb9eb2a801      2
de475a76-4817-591d-921c-fb94da4036bd      1
b5f5dded-8305-50da-a8d8-4754943fe1d5      1
37a25d35-2ce0-5b7d-af61-b0d72114c460      1
Name: count, dtype: int64


--- name.tissue_source_site ---
name.tissue_source_site
MD Anderson Cancer Center                  203
University of Pittsburgh                    74
Vanderbilt University                       54
University Health Network, Toronto          40
UNC                                         36
Johns Hopkins                               21
Greater Poland Cancer Center                20
Barretos Cancer Hospital                    19
International Genomics Consortium           18
Emory University - Winship Cancer Inst.     17
 Fred Hutchinson                            15
University Of Michigan                      14
University of Miami                         13
Asterand                                    13
ABS - IUPUI                                  8
University of Minnesota                      7
Medical College of Georgia                   5
Hartford                                     5
St. University of Colorado Denver            4
Montefiore Medical Center                    3
 Ohio State University                       3
University of Schleswig-Holstein             3
Molecular Response                           2
Memorial Sloan Kettering Cancer Center       2
ILSBio                                       2
Fox Chase                                    1
Duke University                              1
 Boston Medical Center                       1
Name: count, dtype: int64


--- cigarettes_per_day.exposures ---
cigarettes_per_day.exposures
2.191781    39
3.287671    27
1.643836    20
1.095890    17
2.739726    16
            ..
4.712329     1
7.397260     1
0.068493     1
0.049315     1
2.904110     1
Name: count, Length: 87, dtype: int64


--- pack_years_smoked.exposures ---
pack_years_smoked.exposures
40.00     39
60.00     27
30.00     20
20.00     17
50.00     16
          ..
86.00      1
135.00     1
1.25       1
0.90       1
53.00      1
Name: count, Length: 87, dtype: int64


--- age_at_index.demographic ---
age_at_index.demographic
60.0    29
59.0    25
62.0    25
61.0    25
53.0    24
67.0    24
64.0    21
65.0    20
58.0    19
69.0    19
66.0    18
57.0    18
56.0    17
49.0    17
50.0    15
52.0    15
68.0    15
63.0    14
55.0    14
79.0    13
47.0    13
73.0    13
54.0    12
74.0    11
51.0    11
48.0    11
80.0    10
82.0    10
77.0     9
71.0     9
70.0     8
87.0     8
75.0     8
72.0     7
78.0     7
76.0     7
41.0     6
45.0     5
40.0     4
43.0     4
85.0     4
46.0     4
38.0     4
35.0     3
44.0     3
83.0     3
26.0     3
42.0     3
39.0     2
24.0     2
29.0     2
32.0     2
90.0     1
88.0     1
36.0     1
19.0     1
34.0     1
28.0     1
84.0     1
30.0     1
Name: count, dtype: int64


--- tissue_or_organ_of_origin.diagnoses ---
tissue_or_organ_of_origin.diagnoses
Tongue, NOS                                           156
Larynx, NOS                                           139
Overlapping lesion of lip, oral cavity and pharynx     85
Floor of mouth, NOS                                    60
Tonsil, NOS                                            47
Base of tongue, NOS                                    27
Mouth, NOS                                             24
Cheek mucosa                                           19
Hypopharynx, NOS                                        9
Oropharynx, NOS                                         9
Gum, NOS                                                8
Hard palate                                             5
Lip, NOS                                                3
Lower gum                                               2
Anterior floor of mouth                                 2
Border of tongue                                        1
Palate, NOS                                             1
Supraglottis                                            1
Ventral surface of tongue, NOS                          1
Pharynx, NOS                                            1
Retromolar area                                         1
Mandible                                                1
Posterior wall of oropharynx                            1
Upper Gum                                               1
Name: count, dtype: int64


--- primary_diagnosis.diagnoses ---
primary_diagnosis.diagnoses
Squamous cell carcinoma, NOS                                 521
Squamous cell carcinoma, keratinizing, NOS                    61
Squamous cell carcinoma, large cell, nonkeratinizing, NOS     11
Basaloid squamous cell carcinoma                              10
Squamous cell carcinoma, spindle cell                          1
Name: count, dtype: int64

In [15]:
#for dropping columns that we see have only one unique value or are not relevant for our analysis (e.g., disease_type and tumor_grade.diagnoses)

clinical_hnsc_pd_filtered = clinical_hnsc_pd_filtered.drop(columns=["disease_type", "tumor_grade.diagnoses"])
clinical_hnsc_pd_filtered

,sample,sample_type.samples,tissue_type.samples,primary_site,ajcc_pathologic_stage.diagnoses,alcohol_history.exposures,gender.demographic,race.demographic,vital_status.demographic,tissue_source_site_id.tissue_source_site,name.tissue_source_site,cigarettes_per_day.exposures,pack_years_smoked.exposures,age_at_index.demographic,tissue_or_organ_of_origin.diagnoses,primary_diagnosis.diagnoses
0,TCGA-BB-4227-01A,Primary Tumor,Tumor,Hypopharynx,Stage IVA,Yes,male,white,Alive,a7da35ad-149e-5014-932b-37f188536bf8,Johns Hopkins,1.369863,25.0,66.0,"Hypopharynx, NOS","Squamous cell carcinoma, NOS"
1,TCGA-CR-6478-01A,Primary Tumor,Tumor,Tonsil,NaN,Yes,female,white,Dead,041ae4a7-3724-5587-82a9-8e09d3ee3cb8,Vanderbilt University,NaN,NaN,66.0,"Tonsil, NOS","Squamous cell carcinoma, NOS"
2,TCGA-BB-4228-01A,Primary Tumor,Tumor,Base of tongue,Stage III,Yes,male,white,Alive,a7da35ad-149e-5014-932b-37f188536bf8,Johns Hopkins,5.616438,102.5,50.0,"Base of tongue, NOS","Squamous cell carcinoma, NOS"
3,TCGA-BA-4075-01A,Primary Tumor,Tumor,Other and unspecified parts of tongue,Stage III,Yes,male,black or african american,Dead,278e36e9-7faf-5043-ba90-2a4145ad0226,UNC,1.643836,30.0,49.0,"Tongue, NOS","Squamous cell carcinoma, NOS"
4,TCGA-CX-7082-01A,Primary Tumor,Tumor,"Other and ill-defined sites in lip, oral cavit...",Stage IVA,Yes,male,white,Dead,5184bb4b-3075-56fb-886f-7895a42e156b,Medical College of Georgia,2.739726,50.0,82.0,"Overlapping lesion of lip, oral cavity and pha...","Squamous cell carcinoma, NOS"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599,TCGA-CV-7242-11A,Solid Tissue Normal,Normal,Larynx,Stage II,Yes,female,white,Alive,e0529816-35d4-5963-93c3-72c127e4e372,MD Anderson Cancer Center,2.191781,40.0,60.0,"Larynx, NOS","Squamous cell carcinoma, NOS"
600,TCGA-TN-A7HL-01A,Primary Tumor,Tumor,Hypopharynx,Stage IVA,Yes,male,white,Alive,0880c76d-8168-580c-82c0-aeb6ba104840,Ohio State University,0.547945,10.0,59.0,"Hypopharynx, NOS","Squamous cell carcinoma, NOS"
601,TCGA-CV-A6JZ-01A,Primary Tumor,Tumor,Other and unspecified parts of mouth,Stage II,Yes,male,white,Alive,e0529816-35d4-5963-93c3-72c127e4e372,MD Anderson Cancer Center,2.904110,53.0,68.0,"Mouth, NOS","Squamous cell carcinoma, NOS"
602,TCGA-CV-5444-11A,Solid Tissue Normal,Normal,Larynx,Stage IVA,Yes,male,black or african american,Alive,e0529816-35d4-5963-93c3-72c127e4e372,MD Anderson Cancer Center,NaN,NaN,64.0,"Larynx, NOS","Squamous cell carcinoma, NOS"
603,TCGA-CV-5444-01A,Primary Tumor,Tumor,Larynx,Stage IVA,Yes,male,black or african american,Alive,e0529816-35d4-5963-93c3-72c127e4e372,MD Anderson Cancer Center,NaN,NaN,64.0,"Larynx, NOS","Squamous cell carcinoma, NOS"

In [16]:
clinical_hnsc_pd_filtered.isna().sum()

sample                                        0
sample_type.samples                           0
tissue_type.samples                           0
primary_site                                  0
ajcc_pathologic_stage.diagnoses              76
alcohol_history.exposures                     0
gender.demographic                            0
race.demographic                              0
vital_status.demographic                      0
tissue_source_site_id.tissue_source_site      0
name.tissue_source_site                       0
cigarettes_per_day.exposures                282
pack_years_smoked.exposures                 282
age_at_index.demographic                      1
tissue_or_organ_of_origin.diagnoses           0
primary_diagnosis.diagnoses                   0
dtype: int64

In [17]:
clinical_hnsc_pd_filtered['ajcc_pathologic_stage.diagnoses'] = clinical_hnsc_pd_filtered['ajcc_pathologic_stage.diagnoses'].fillna('Unknown')
clinical_hnsc_pd_filtered.isna().sum()

sample                                        0
sample_type.samples                           0
tissue_type.samples                           0
primary_site                                  0
ajcc_pathologic_stage.diagnoses               0
alcohol_history.exposures                     0
gender.demographic                            0
race.demographic                              0
vital_status.demographic                      0
tissue_source_site_id.tissue_source_site      0
name.tissue_source_site                       0
cigarettes_per_day.exposures                282
pack_years_smoked.exposures                 282
age_at_index.demographic                      1
tissue_or_organ_of_origin.diagnoses           0
primary_diagnosis.diagnoses                   0
dtype: int64

In [18]:
clinical_hnsc_all = clinical_hnsc_pd_filtered.copy()
#clinical_hnsc_pd_filtered_tumor = clinical_hnsc_pd_filtered[clinical_hnsc_pd_filtered['sample_type.samples'] == 'Primary Tumor']

In [19]:
# 1. Extract the valid sample IDs from your clinical dataframe into a list
#valid_tumor_samples = clinical_hnsc_pd_filtered_tumor['sample'].tolist()
valid_all_samples = clinical_hnsc_all['sample'].tolist() # Assuming you have this too

# 2. Filter the methylation dataframe keeping only rows where the Index matches the list
#methylation_hnsc_pd_tumor = methylation_hnsc_pd[methylation_hnsc_pd.index.isin(valid_tumor_samples)]
methylation_hnsc_all = methylation_hnsc_pd[methylation_hnsc_pd.index.isin(valid_all_samples)]

In [20]:
methylation_hnsc_all

Composite Element REF,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000292,cg00000321,cg00000363,cg00000622,cg00000658,...,ctl_70664314,ctl_70700334,ctl_71670310,ctl_71678368,ctl_71718498,ctl_72748406,ctl_73635489,ctl_73784382,ctl_73794434,ctl_74666473
TCGA-F7-A61V-01A,0.169494,0.969504,0.901731,0.575925,0.884583,0.443790,0.527111,0.201535,0.016330,0.899096,...,0.024935,0.074955,0.934347,0.074081,0.109095,0.123795,0.055536,0.893430,0.924984,0.958676
TCGA-CV-7407-01A,0.271910,0.968134,0.955765,0.643235,0.934308,0.772394,0.736274,0.313491,0.014606,0.832098,...,0.097556,0.054384,0.965121,0.051201,0.218709,0.076075,0.070833,0.929056,0.972468,0.952202
TCGA-UF-A7JO-01A,0.417004,0.955937,0.921865,0.488987,0.906538,0.757155,0.564353,0.325092,0.015789,0.843975,...,0.028748,0.091012,0.960164,0.055483,0.166570,0.120988,0.063425,0.931578,0.951702,0.964257
TCGA-CV-6948-01A,0.128467,0.968904,0.910797,0.860205,0.921293,0.547383,0.674936,0.230438,0.012691,0.889466,...,0.039361,0.055663,0.960194,0.065371,0.177939,0.097036,0.088908,0.936490,0.955121,0.957882
TCGA-BB-7864-01A,0.171842,0.958299,0.945290,0.723734,0.904258,0.461953,0.285278,0.221449,0.013150,0.889051,...,0.023655,0.063635,0.968602,0.053799,0.178144,0.092968,0.052888,0.955130,0.970614,0.968689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-CV-7432-01A,0.485641,0.954409,0.937185,0.734791,0.917020,0.736587,0.466652,0.435981,0.015868,0.806900,...,0.129434,0.072841,0.966988,0.078038,0.219387,0.115900,0.061564,0.921702,0.956045,0.957312
TCGA-CR-6471-01A,0.393504,0.957079,0.929260,0.705929,0.926273,0.733265,0.559355,0.275917,0.017546,0.878021,...,0.070154,0.101726,0.949204,0.053345,0.188774,0.124597,0.066099,0.938521,0.953174,0.978739
TCGA-MT-A67A-01A,0.606525,0.958249,0.923488,0.499184,0.919832,0.665014,0.574861,0.346464,0.012115,0.844069,...,0.018265,0.086160,0.967759,0.055477,0.086231,0.102222,0.062569,0.944587,0.963469,0.959490
TCGA-H7-7774-01A,0.561132,0.973065,0.924097,0.692248,0.930900,0.749997,0.654586,0.266455,0.015712,0.873654,...,0.080932,0.058969,0.967671,0.056863,0.184611,0.072771,0.062440,0.944116,0.960702,0.952825
TCGA-CV-7415-01A,0.162578,0.939583,0.943951,0.763323,0.922248,0.740405,0.569332,0.249119,0.013830,0.877001,...,0.088900,0.074435,0.962625,0.096838,0.202180,0.092403,0.065178,0.941396,0.963867,0.959952

In [21]:
#save the filtered dataframes for later use
methylation_hnsc_all.to_csv('../data/processed/methylation_hnsc_all.csv')
#methylation_hnsc_pd_tumor.to_csv('../data/processed/methylation_hnsc_pd_tumor.csv')
clinical_hnsc_all.to_csv('../data/processed/clinical_hnsc_all.csv')
#clinical_hnsc_pd_filtered_tumor.to_csv('../data/processed/clinical_hnsc_pd_filtered_tumor.csv')

In [22]:
clinical_hnsc_all

,sample,sample_type.samples,tissue_type.samples,primary_site,ajcc_pathologic_stage.diagnoses,alcohol_history.exposures,gender.demographic,race.demographic,vital_status.demographic,tissue_source_site_id.tissue_source_site,name.tissue_source_site,cigarettes_per_day.exposures,pack_years_smoked.exposures,age_at_index.demographic,tissue_or_organ_of_origin.diagnoses,primary_diagnosis.diagnoses
0,TCGA-BB-4227-01A,Primary Tumor,Tumor,Hypopharynx,Stage IVA,Yes,male,white,Alive,a7da35ad-149e-5014-932b-37f188536bf8,Johns Hopkins,1.369863,25.0,66.0,"Hypopharynx, NOS","Squamous cell carcinoma, NOS"
1,TCGA-CR-6478-01A,Primary Tumor,Tumor,Tonsil,Unknown,Yes,female,white,Dead,041ae4a7-3724-5587-82a9-8e09d3ee3cb8,Vanderbilt University,NaN,NaN,66.0,"Tonsil, NOS","Squamous cell carcinoma, NOS"
2,TCGA-BB-4228-01A,Primary Tumor,Tumor,Base of tongue,Stage III,Yes,male,white,Alive,a7da35ad-149e-5014-932b-37f188536bf8,Johns Hopkins,5.616438,102.5,50.0,"Base of tongue, NOS","Squamous cell carcinoma, NOS"
3,TCGA-BA-4075-01A,Primary Tumor,Tumor,Other and unspecified parts of tongue,Stage III,Yes,male,black or african american,Dead,278e36e9-7faf-5043-ba90-2a4145ad0226,UNC,1.643836,30.0,49.0,"Tongue, NOS","Squamous cell carcinoma, NOS"
4,TCGA-CX-7082-01A,Primary Tumor,Tumor,"Other and ill-defined sites in lip, oral cavit...",Stage IVA,Yes,male,white,Dead,5184bb4b-3075-56fb-886f-7895a42e156b,Medical College of Georgia,2.739726,50.0,82.0,"Overlapping lesion of lip, oral cavity and pha...","Squamous cell carcinoma, NOS"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599,TCGA-CV-7242-11A,Solid Tissue Normal,Normal,Larynx,Stage II,Yes,female,white,Alive,e0529816-35d4-5963-93c3-72c127e4e372,MD Anderson Cancer Center,2.191781,40.0,60.0,"Larynx, NOS","Squamous cell carcinoma, NOS"
600,TCGA-TN-A7HL-01A,Primary Tumor,Tumor,Hypopharynx,Stage IVA,Yes,male,white,Alive,0880c76d-8168-580c-82c0-aeb6ba104840,Ohio State University,0.547945,10.0,59.0,"Hypopharynx, NOS","Squamous cell carcinoma, NOS"
601,TCGA-CV-A6JZ-01A,Primary Tumor,Tumor,Other and unspecified parts of mouth,Stage II,Yes,male,white,Alive,e0529816-35d4-5963-93c3-72c127e4e372,MD Anderson Cancer Center,2.904110,53.0,68.0,"Mouth, NOS","Squamous cell carcinoma, NOS"
602,TCGA-CV-5444-11A,Solid Tissue Normal,Normal,Larynx,Stage IVA,Yes,male,black or african american,Alive,e0529816-35d4-5963-93c3-72c127e4e372,MD Anderson Cancer Center,NaN,NaN,64.0,"Larynx, NOS","Squamous cell carcinoma, NOS"
603,TCGA-CV-5444-01A,Primary Tumor,Tumor,Larynx,Stage IVA,Yes,male,black or african american,Alive,e0529816-35d4-5963-93c3-72c127e4e372,MD Anderson Cancer Center,NaN,NaN,64.0,"Larynx, NOS","Squamous cell carcinoma, NOS"

In [23]:
methylation_hnsc_all

Composite Element REF,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000292,cg00000321,cg00000363,cg00000622,cg00000658,...,ctl_70664314,ctl_70700334,ctl_71670310,ctl_71678368,ctl_71718498,ctl_72748406,ctl_73635489,ctl_73784382,ctl_73794434,ctl_74666473
TCGA-F7-A61V-01A,0.169494,0.969504,0.901731,0.575925,0.884583,0.443790,0.527111,0.201535,0.016330,0.899096,...,0.024935,0.074955,0.934347,0.074081,0.109095,0.123795,0.055536,0.893430,0.924984,0.958676
TCGA-CV-7407-01A,0.271910,0.968134,0.955765,0.643235,0.934308,0.772394,0.736274,0.313491,0.014606,0.832098,...,0.097556,0.054384,0.965121,0.051201,0.218709,0.076075,0.070833,0.929056,0.972468,0.952202
TCGA-UF-A7JO-01A,0.417004,0.955937,0.921865,0.488987,0.906538,0.757155,0.564353,0.325092,0.015789,0.843975,...,0.028748,0.091012,0.960164,0.055483,0.166570,0.120988,0.063425,0.931578,0.951702,0.964257
TCGA-CV-6948-01A,0.128467,0.968904,0.910797,0.860205,0.921293,0.547383,0.674936,0.230438,0.012691,0.889466,...,0.039361,0.055663,0.960194,0.065371,0.177939,0.097036,0.088908,0.936490,0.955121,0.957882
TCGA-BB-7864-01A,0.171842,0.958299,0.945290,0.723734,0.904258,0.461953,0.285278,0.221449,0.013150,0.889051,...,0.023655,0.063635,0.968602,0.053799,0.178144,0.092968,0.052888,0.955130,0.970614,0.968689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-CV-7432-01A,0.485641,0.954409,0.937185,0.734791,0.917020,0.736587,0.466652,0.435981,0.015868,0.806900,...,0.129434,0.072841,0.966988,0.078038,0.219387,0.115900,0.061564,0.921702,0.956045,0.957312
TCGA-CR-6471-01A,0.393504,0.957079,0.929260,0.705929,0.926273,0.733265,0.559355,0.275917,0.017546,0.878021,...,0.070154,0.101726,0.949204,0.053345,0.188774,0.124597,0.066099,0.938521,0.953174,0.978739
TCGA-MT-A67A-01A,0.606525,0.958249,0.923488,0.499184,0.919832,0.665014,0.574861,0.346464,0.012115,0.844069,...,0.018265,0.086160,0.967759,0.055477,0.086231,0.102222,0.062569,0.944587,0.963469,0.959490
TCGA-H7-7774-01A,0.561132,0.973065,0.924097,0.692248,0.930900,0.749997,0.654586,0.266455,0.015712,0.873654,...,0.080932,0.058969,0.967671,0.056863,0.184611,0.072771,0.062440,0.944116,0.960702,0.952825
TCGA-CV-7415-01A,0.162578,0.939583,0.943951,0.763323,0.922248,0.740405,0.569332,0.249119,0.013830,0.877001,...,0.088900,0.074435,0.962625,0.096838,0.202180,0.092403,0.065178,0.941396,0.963867,0.959952