In [1]:
import sys
import os

# 1. Get the path to the parent directory (project_root)
parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))

# 2. Add the parent directory to Python's system path
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

# 3. Import your functions
from src.preprocess_01 import print_hello

In [2]:
print_hello()

Hello, import successful!

In [3]:
import pandas as pd
import numpy as np

clinical_lihc_pd = pd.read_csv('../data/raw/TCGA-LIHC.clinical.tsv', sep='\t')
methylation_lihc_pd = pd.read_csv('../data/raw/TCGA-LIHC.methylation450.tsv', sep='\t')

In [4]:
methylation_lihc_pd

,Composite Element REF,TCGA-DD-A73D-01A,TCGA-G3-A5SK-01A,TCGA-DD-A1EL-11A,TCGA-DD-AAD8-01A,TCGA-WX-AA47-01A,TCGA-DD-A1EL-01A,TCGA-G3-A3CH-01A,TCGA-ZP-A9CZ-01A,TCGA-ZS-A9CG-01A,...,TCGA-DD-AACY-01A,TCGA-DD-AADY-01A,TCGA-BD-A3EP-01A,TCGA-BC-A8YO-01A,TCGA-G3-AAV3-01A,TCGA-RC-A7S9-01A,TCGA-CC-A9FS-01A,TCGA-DD-AAEB-01A,TCGA-EP-A3RK-01A,TCGA-GJ-A3OU-01A
0,cg00000029,0.462948,0.549508,0.483441,NaN,0.247690,0.243003,0.462684,0.574164,0.692021,...,0.511327,0.184897,0.437332,NaN,0.719458,0.117426,0.755458,0.661787,0.475990,0.353968
1,cg00000108,0.117137,0.428748,0.590056,0.164315,0.259369,0.619059,0.951956,0.680627,0.598668,...,0.248294,0.435341,0.647230,0.781436,0.569249,0.727903,0.967289,0.321233,0.731066,0.720276
2,cg00000109,0.924546,0.908687,0.962914,0.802248,0.913790,0.844312,0.938847,0.915398,0.906425,...,0.755895,0.859881,0.944584,0.887024,0.877040,0.917399,0.891528,0.869649,0.876023,0.917732
3,cg00000165,0.105907,0.180788,0.112548,0.134154,0.111872,0.093518,0.208059,0.213224,0.139133,...,NaN,NaN,0.182530,NaN,0.372131,0.137528,0.804547,0.156531,0.172246,0.235252
4,cg00000236,0.943050,0.918806,0.853267,0.855616,0.931874,0.866817,0.926413,0.937136,0.892341,...,0.887098,0.899817,0.935812,0.869131,0.918356,0.879191,0.860259,0.865454,0.951141,0.907275
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486422,rs9363764,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486423,rs939290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486424,rs951295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486425,rs966367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486426,rs9839873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
clinical_lihc_pd

,sample,id,disease_type,case_id,submitter_id,primary_site,alcohol_history.exposures,race.demographic,gender.demographic,ethnicity.demographic,...,sample_type.samples,composition.samples,days_to_collection.samples,initial_weight.samples,preservation_method.samples,pathology_report_uuid.samples,oct_embedded.samples,specimen_type.samples,is_ffpe.samples,tissue_type.samples
0,TCGA-DD-A73C-01A,79f9331c-9e00-4277-a9d1-7c848e132134,Adenomas and Adenocarcinomas,79f9331c-9e00-4277-a9d1-7c848e132134,TCGA-DD-A73C,Liver and intrahepatic bile ducts,Not Reported,white,female,not hispanic or latino,...,Primary Tumor,Not Reported,288.0,160.0,Unknown,FE051CD7-9C34-4A45-934C-DD8BB00C717A,False,Solid Tissue,False,Tumor
1,TCGA-5C-AAPD-01A,7a6162a4-1166-4310-84cd-ffc2b06f124c,Adenomas and Adenocarcinomas,7a6162a4-1166-4310-84cd-ffc2b06f124c,TCGA-5C-AAPD,Liver and intrahepatic bile ducts,Not Reported,asian,male,not hispanic or latino,...,Primary Tumor,Not Reported,55.0,140.0,OCT,E4DB31C4-89F3-4D8D-A32E-B42C599904E1,True,Solid Tissue,False,Tumor
2,TCGA-ZS-A9CE-01A,7bdc5f86-4d7d-4f1f-bc23-ab51fa9fb947,Adenomas and Adenocarcinomas,7bdc5f86-4d7d-4f1f-bc23-ab51fa9fb947,TCGA-ZS-A9CE,Liver and intrahepatic bile ducts,Not Reported,white,female,not hispanic or latino,...,Primary Tumor,Not Reported,967.0,10.0,OCT,35A87F65-19F9-4C03-8A82-FFBF2C3C568A,True,Solid Tissue,False,Tumor
3,TCGA-HP-A5N0-01A,7f8e25d4-6021-4327-96ab-79b6fcc97a24,Adenomas and Adenocarcinomas,7f8e25d4-6021-4327-96ab-79b6fcc97a24,TCGA-HP-A5N0,Liver and intrahepatic bile ducts,Not Reported,not reported,female,not reported,...,Primary Tumor,Not Reported,NaN,350.0,Unknown,0221A6F3-34F5-407E-8548-B62F27F66FCE,False,Solid Tissue,False,Tumor
4,TCGA-DD-AAVQ-01A,80e7742f-abbe-4f11-b4e4-c999dc1bd459,Adenomas and Adenocarcinomas,80e7742f-abbe-4f11-b4e4-c999dc1bd459,TCGA-DD-AAVQ,Liver and intrahepatic bile ducts,Not Reported,asian,male,not hispanic or latino,...,Primary Tumor,Not Reported,2464.0,80.0,OCT,A58E32BF-829C-48AB-BC80-919A295D78D5,True,Solid Tissue,False,Tumor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434,TCGA-DD-A73E-01A,e0863874-f7b8-49b6-a88b-5ae5f1ec2b15,Adenomas and Adenocarcinomas,e0863874-f7b8-49b6-a88b-5ae5f1ec2b15,TCGA-DD-A73E,Liver and intrahepatic bile ducts,Not Reported,white,male,not hispanic or latino,...,Primary Tumor,Not Reported,336.0,170.0,Unknown,10881D8D-1C62-4F3D-ACF6-36AD1F23B0A9,False,Solid Tissue,False,Tumor
435,TCGA-CC-A7IH-01A,e4e0bc11-ad61-4419-857c-44fb5c7877a3,Adenomas and Adenocarcinomas,e4e0bc11-ad61-4419-857c-44fb5c7877a3,TCGA-CC-A7IH,Liver and intrahepatic bile ducts,Not Reported,asian,male,not hispanic or latino,...,Primary Tumor,Not Reported,181.0,190.0,OCT,643C84D1-C247-4CA6-84C3-38ED99E886F6,True,Solid Tissue,False,Tumor
436,TCGA-BW-A5NO-01A,ee63c44b-91f4-4004-8dea-192eab527036,Adenomas and Adenocarcinomas,ee63c44b-91f4-4004-8dea-192eab527036,TCGA-BW-A5NO,Liver and intrahepatic bile ducts,Not Reported,black or african american,male,not hispanic or latino,...,Primary Tumor,Not Reported,840.0,110.0,Unknown,39E090EF-9EA0-4362-BB47-432DE5AA1393,False,Solid Tissue,False,Tumor
437,TCGA-2Y-A9H9-01A,efc3e5e4-0d8e-4bef-a259-29f8ed21684f,Adenomas and Adenocarcinomas,efc3e5e4-0d8e-4bef-a259-29f8ed21684f,TCGA-2Y-A9H9,Liver and intrahepatic bile ducts,Not Reported,white,male,not hispanic or latino,...,Primary Tumor,Not Reported,731.0,120.0,OCT,36C343AC-443B-4196-8B6D-7D9213F2DAE1,True,Solid Tissue,False,Tumor
438,TCGA-RC-A7S9-01A,f5de6712-4de4-43de-8eb5-ec2a798c8438,Adenomas and Adenocarcinomas,f5de6712-4de4-43de-8eb5-ec2a798c8438,TCGA-RC-A7S9,Liver and intrahepatic bile ducts,Not Reported,asian,female,not hispanic or latino,...,Primary Tumor,Not Reported,383.0,20.0,OCT,A537996A-E747-4906-B488-43181F3C7E17,True,Solid Tissue,False,Tumor

In [6]:
#transpose the methylation dataframe

methylation_lihc_pd.set_index('Composite Element REF', inplace=True)
methylation_lihc_pd_old = methylation_lihc_pd.transpose()
methylation_lihc_pd_old

Composite Element REF,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs7746156,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873
TCGA-DD-A73D-01A,0.462948,0.117137,0.924546,0.105907,0.943050,0.835638,0.657382,0.076094,0.851907,0.014520,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCGA-G3-A5SK-01A,0.549508,0.428748,0.908687,0.180788,0.918806,0.686327,0.676207,0.198359,0.751913,0.014256,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCGA-DD-A1EL-11A,0.483441,0.590056,0.962914,0.112548,0.853267,0.820589,0.811190,0.254828,0.615154,0.013704,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCGA-DD-AAD8-01A,NaN,0.164315,0.802248,0.134154,0.855616,NaN,0.719729,0.121652,0.642324,0.011543,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCGA-WX-AA47-01A,0.247690,0.259369,0.913790,0.111872,0.931874,0.700367,0.792509,0.083664,0.800295,0.015096,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-RC-A7S9-01A,0.117426,0.727903,0.917399,0.137528,0.879191,0.770096,0.498206,0.248408,0.859052,0.012922,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCGA-CC-A9FS-01A,0.755458,0.967289,0.891528,0.804547,0.860259,NaN,0.945034,0.676335,0.754555,0.013039,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCGA-DD-AAEB-01A,0.661787,0.321233,0.869649,0.156531,0.865454,NaN,0.610651,0.127981,0.860820,0.011846,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCGA-EP-A3RK-01A,0.475990,0.731066,0.876023,0.172246,0.951141,0.810197,0.853662,0.243828,0.721904,0.011956,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCGA-GJ-A3OU-01A,0.353968,0.720276,0.917732,0.235252,0.907275,0.834036,0.848464,0.351756,0.572167,0.016130,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
import pandas as pd
from sklearn.impute import SimpleImputer

# --- STEP 1: Drop probes with too many NaNs ---
# Calculate the threshold for 10% missingness
# (e.g., if you have 370 tumor samples, keep probes that have at least 333 valid values)
threshold = int(methylation_lihc_pd_old.shape[0] * 0.90)

# Drop columns (probes) that do not meet the threshold
methylation_lihc_pd = methylation_lihc_pd_old.dropna(axis=1, thresh=threshold)

print(f"Original probes: {methylation_lihc_pd_old.shape[1]}")
print(f"Probes after dropping bad ones: {methylation_lihc_pd.shape[1]}")

Original probes: 486427
Probes after dropping bad ones: 383815

In [8]:
methylation_lihc_pd

Composite Element REF,cg00000108,cg00000109,cg00000236,cg00000292,cg00000321,cg00000363,cg00000622,cg00000658,cg00000714,cg00000721,...,ctl_70664314,ctl_70700334,ctl_71670310,ctl_71678368,ctl_71718498,ctl_72748406,ctl_73635489,ctl_73784382,ctl_73794434,ctl_74666473
TCGA-DD-A73D-01A,0.117137,0.924546,0.943050,0.657382,0.076094,0.851907,0.014520,0.796828,0.408849,0.959089,...,0.016190,0.058347,0.963264,0.056226,0.109904,0.098351,0.066046,0.939816,0.955241,0.961276
TCGA-G3-A5SK-01A,0.428748,0.908687,0.918806,0.676207,0.198359,0.751913,0.014256,0.840600,0.167963,0.957603,...,0.017244,0.096494,0.956808,0.075496,0.095065,0.097984,0.088078,0.931223,0.946813,0.957117
TCGA-DD-A1EL-11A,0.590056,0.962914,0.853267,0.811190,0.254828,0.615154,0.013704,0.903124,0.248404,0.961450,...,0.048371,0.050236,0.957189,0.051330,0.178029,0.067013,0.052013,0.942271,0.952217,0.967854
TCGA-DD-AAD8-01A,0.164315,0.802248,0.855616,0.719729,0.121652,0.642324,0.011543,0.845569,0.113078,0.937181,...,0.026267,0.101110,0.912187,0.114697,0.111062,NaN,0.110835,0.893607,0.792508,0.960780
TCGA-WX-AA47-01A,0.259369,0.913790,0.931874,0.792509,0.083664,0.800295,0.015096,0.822098,0.109717,0.947942,...,0.022311,0.105520,0.955789,0.060052,0.101830,0.100906,0.081402,0.934609,0.938779,0.969138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-RC-A7S9-01A,0.727903,0.917399,0.879191,0.498206,0.248408,0.859052,0.012922,0.864288,0.097928,0.929429,...,0.017357,0.062147,0.960526,0.056585,0.099479,0.102135,0.066599,0.934101,0.948080,0.963495
TCGA-CC-A9FS-01A,0.967289,0.891528,0.860259,0.945034,0.676335,0.754555,0.013039,0.840799,0.107899,0.933557,...,0.026578,0.091685,0.919480,0.098662,0.094480,0.110258,0.170863,0.852174,0.930500,0.967402
TCGA-DD-AAEB-01A,0.321233,0.869649,0.865454,0.610651,0.127981,0.860820,0.011846,0.846064,0.184822,0.273931,...,0.022636,0.091522,0.937423,0.093921,0.129181,NaN,0.078684,0.896254,0.891230,0.959803
TCGA-EP-A3RK-01A,0.731066,0.876023,0.951141,0.853662,0.243828,0.721904,0.011956,0.845202,0.172222,0.957277,...,0.015384,0.065589,0.961302,0.058295,0.103602,0.091236,0.063071,0.949478,0.962490,0.960636
TCGA-GJ-A3OU-01A,0.720276,0.917732,0.907275,0.848464,0.351756,0.572167,0.016130,0.828588,0.206280,0.950362,...,0.054325,0.090232,0.946123,0.054699,0.194749,0.140927,0.065614,0.951649,0.959182,0.968255

In [9]:
# --- STEP 2: Impute remaining NaNs ---
# Initialize the imputer to fill NaNs with the median value of each column
imputer = SimpleImputer(strategy='median')

# Fit and transform the data (Note: this returns a numpy array)
methylation_imputed_array = imputer.fit_transform(methylation_lihc_pd)

# Convert back to a pandas DataFrame to keep your Patient IDs and Probe IDs safe
methylation_lihc_pd = pd.DataFrame(
    methylation_imputed_array,
    index=methylation_lihc_pd.index,      # Patient IDs
    columns=methylation_lihc_pd.columns   # CpG Probe IDs
)

print(f"Total NaNs remaining: {methylation_lihc_pd.isna().sum().sum()}")

Total NaNs remaining: 0

In [10]:
methylation_lihc_pd

Composite Element REF,cg00000108,cg00000109,cg00000236,cg00000292,cg00000321,cg00000363,cg00000622,cg00000658,cg00000714,cg00000721,...,ctl_70664314,ctl_70700334,ctl_71670310,ctl_71678368,ctl_71718498,ctl_72748406,ctl_73635489,ctl_73784382,ctl_73794434,ctl_74666473
TCGA-DD-A73D-01A,0.117137,0.924546,0.943050,0.657382,0.076094,0.851907,0.014520,0.796828,0.408849,0.959089,...,0.016190,0.058347,0.963264,0.056226,0.109904,0.098351,0.066046,0.939816,0.955241,0.961276
TCGA-G3-A5SK-01A,0.428748,0.908687,0.918806,0.676207,0.198359,0.751913,0.014256,0.840600,0.167963,0.957603,...,0.017244,0.096494,0.956808,0.075496,0.095065,0.097984,0.088078,0.931223,0.946813,0.957117
TCGA-DD-A1EL-11A,0.590056,0.962914,0.853267,0.811190,0.254828,0.615154,0.013704,0.903124,0.248404,0.961450,...,0.048371,0.050236,0.957189,0.051330,0.178029,0.067013,0.052013,0.942271,0.952217,0.967854
TCGA-DD-AAD8-01A,0.164315,0.802248,0.855616,0.719729,0.121652,0.642324,0.011543,0.845569,0.113078,0.937181,...,0.026267,0.101110,0.912187,0.114697,0.111062,0.117661,0.110835,0.893607,0.792508,0.960780
TCGA-WX-AA47-01A,0.259369,0.913790,0.931874,0.792509,0.083664,0.800295,0.015096,0.822098,0.109717,0.947942,...,0.022311,0.105520,0.955789,0.060052,0.101830,0.100906,0.081402,0.934609,0.938779,0.969138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-RC-A7S9-01A,0.727903,0.917399,0.879191,0.498206,0.248408,0.859052,0.012922,0.864288,0.097928,0.929429,...,0.017357,0.062147,0.960526,0.056585,0.099479,0.102135,0.066599,0.934101,0.948080,0.963495
TCGA-CC-A9FS-01A,0.967289,0.891528,0.860259,0.945034,0.676335,0.754555,0.013039,0.840799,0.107899,0.933557,...,0.026578,0.091685,0.919480,0.098662,0.094480,0.110258,0.170863,0.852174,0.930500,0.967402
TCGA-DD-AAEB-01A,0.321233,0.869649,0.865454,0.610651,0.127981,0.860820,0.011846,0.846064,0.184822,0.273931,...,0.022636,0.091522,0.937423,0.093921,0.129181,0.117661,0.078684,0.896254,0.891230,0.959803
TCGA-EP-A3RK-01A,0.731066,0.876023,0.951141,0.853662,0.243828,0.721904,0.011956,0.845202,0.172222,0.957277,...,0.015384,0.065589,0.961302,0.058295,0.103602,0.091236,0.063071,0.949478,0.962490,0.960636
TCGA-GJ-A3OU-01A,0.720276,0.917732,0.907275,0.848464,0.351756,0.572167,0.016130,0.828588,0.206280,0.950362,...,0.054325,0.090232,0.946123,0.054699,0.194749,0.140927,0.065614,0.951649,0.959182,0.968255

In [11]:
clinical_lihc_pd.columns

Index(['sample', 'id', 'disease_type', 'case_id', 'submitter_id',
       'primary_site', 'alcohol_history.exposures', 'race.demographic',
       'gender.demographic', 'ethnicity.demographic',
       'vital_status.demographic', 'age_at_index.demographic',
       'days_to_birth.demographic', 'year_of_birth.demographic',
       'year_of_death.demographic', 'primary_site.project',
       'project_id.project', 'disease_type.project', 'name.project',
       'name.program.project', 'tissue_source_site_id.tissue_source_site',
       'code.tissue_source_site', 'name.tissue_source_site',
       'project.tissue_source_site', 'bcr_id.tissue_source_site',
       'days_to_death.demographic', 'entity_submitter_id.annotations',
       'notes.annotations', 'submitter_id.annotations',
       'classification.annotations', 'entity_id.annotations',
       'created_datetime.annotations', 'annotation_id.annotations',
       'entity_type.annotations', 'updated_datetime.annotations',
       'case_id.annotations', 'state.annotations', 'category.annotations',
       'status.annotations', 'case_submitter_id.annotations',
       'synchronous_malignancy.diagnoses', 'ajcc_pathologic_stage.diagnoses',
       'days_to_diagnosis.diagnoses', 'last_known_disease_status.diagnoses',
       'tissue_or_organ_of_origin.diagnoses',
       'days_to_last_follow_up.diagnoses', 'age_at_diagnosis.diagnoses',
       'primary_diagnosis.diagnoses', 'prior_malignancy.diagnoses',
       'year_of_diagnosis.diagnoses', 'prior_treatment.diagnoses',
       'ajcc_staging_system_edition.diagnoses', 'ajcc_pathologic_t.diagnoses',
       'morphology.diagnoses', 'ajcc_pathologic_n.diagnoses',
       'ajcc_pathologic_m.diagnoses', 'classification_of_tumor.diagnoses',
       'icd_10_code.diagnoses', 'site_of_resection_or_biopsy.diagnoses',
       'tumor_grade.diagnoses', 'progression_or_recurrence.diagnoses',
       'age_at_earliest_diagnosis.diagnoses.xena_derived',
       'age_at_earliest_diagnosis_in_years.diagnoses.xena_derived',
       'treatment_id.treatments.diagnoses',
       'submitter_id.treatments.diagnoses',
       'treatment_type.treatments.diagnoses',
       'treatment_or_therapy.treatments.diagnoses',
       'created_datetime.treatments.diagnoses',
       'updated_datetime.treatments.diagnoses', 'state.treatments.diagnoses',
       'sample_type_id.samples', 'tumor_descriptor.samples',
       'sample_id.samples', 'sample_type.samples', 'composition.samples',
       'days_to_collection.samples', 'initial_weight.samples',
       'preservation_method.samples', 'pathology_report_uuid.samples',
       'oct_embedded.samples', 'specimen_type.samples', 'is_ffpe.samples',
       'tissue_type.samples'],
      dtype='object')

In [12]:
columns_to_keep = [
    # --- Identifiers & Subsetting ---
    'sample',                                  # Keep as index to match methylation matrix
    'sample_type.samples',                     # Essential: For subsetting (Tumor vs Normal)
    'tissue_type.samples',                     # Alternative/backup for subsetting
    
    # --- Disease Scope (Useful if merging with other TCGA cohorts later) ---
    'disease_type',                            # e.g., Liver Hepatocellular Carcinoma
    'primary_site',                            # e.g., Liver
    
    # --- Clinical & Progression ---
    'tumor_grade.diagnoses',                   # Highly correlated with methylation changes
    'ajcc_pathologic_stage.diagnoses',         # Overall disease stage
    
    # --- Risk Factors & Demographics ---
    'alcohol_history.exposures',               # Major epigenetic driver in LIHC
    'gender.demographic',                      # Strong bias in LIHC / Check for sex chromosome filtering
    'race.demographic',                        # Check for disparities/patterns
    'vital_status.demographic',                # Survival correlation
    
    # --- Technical / Batch Effect Checking ---
    'tissue_source_site_id.tissue_source_site',# ID of the collection hospital
    'name.tissue_source_site'                  # Name of the collection hospital
]

# Filter your phenotype dataframe
clinical_lihc_pd_filtered = clinical_lihc_pd[columns_to_keep]
clinical_lihc_pd_filtered

,sample,sample_type.samples,tissue_type.samples,disease_type,primary_site,tumor_grade.diagnoses,ajcc_pathologic_stage.diagnoses,alcohol_history.exposures,gender.demographic,race.demographic,vital_status.demographic,tissue_source_site_id.tissue_source_site,name.tissue_source_site
0,TCGA-DD-A73C-01A,Primary Tumor,Tumor,Adenomas and Adenocarcinomas,Liver and intrahepatic bile ducts,Not Reported,Stage IIIA,Not Reported,female,white,Alive,c2eb5c30-93cc-5a99-b9e4-f676e35ed7f8,Mayo Clinic - Rochester
1,TCGA-5C-AAPD-01A,Primary Tumor,Tumor,Adenomas and Adenocarcinomas,Liver and intrahepatic bile ducts,Not Reported,Stage II,Not Reported,male,asian,Alive,994ff94f-5d44-5de6-908b-dea33dca2a3d,Cureline
2,TCGA-ZS-A9CE-01A,Primary Tumor,Tumor,Adenomas and Adenocarcinomas,Liver and intrahepatic bile ducts,Not Reported,Stage II,Not Reported,female,white,Alive,33a38997-77be-52dc-b79d-890d8d4b792b,Tayside Tissue Bank
3,TCGA-HP-A5N0-01A,Primary Tumor,Tumor,Adenomas and Adenocarcinomas,Liver and intrahepatic bile ducts,Not Reported,NaN,Not Reported,female,not reported,Dead,b521e8d8-2b93-5a14-9fd0-ece883fd1327,Ontario Institute for Cancer Research (OICR)
4,TCGA-DD-AAVQ-01A,Primary Tumor,Tumor,Adenomas and Adenocarcinomas,Liver and intrahepatic bile ducts,Not Reported,Stage I,Not Reported,male,asian,Alive,c2eb5c30-93cc-5a99-b9e4-f676e35ed7f8,Mayo Clinic - Rochester
...,...,...,...,...,...,...,...,...,...,...,...,...,...
434,TCGA-DD-A73E-01A,Primary Tumor,Tumor,Adenomas and Adenocarcinomas,Liver and intrahepatic bile ducts,Not Reported,Stage I,Not Reported,male,white,Alive,c2eb5c30-93cc-5a99-b9e4-f676e35ed7f8,Mayo Clinic - Rochester
435,TCGA-CC-A7IH-01A,Primary Tumor,Tumor,Adenomas and Adenocarcinomas,Liver and intrahepatic bile ducts,Not Reported,Stage IIIA,Not Reported,male,asian,Alive,be652f28-50ec-5d4e-bc42-79a304ee03db,ILSBio
436,TCGA-BW-A5NO-01A,Primary Tumor,Tumor,Adenomas and Adenocarcinomas,Liver and intrahepatic bile ducts,Not Reported,Stage IIIA,Not Reported,male,black or african american,Alive,0e691470-b18b-5803-9e4a-ee2cfbaae7b4,St. Joseph's Medical Center-(MD)
437,TCGA-2Y-A9H9-01A,Primary Tumor,Tumor,Adenomas and Adenocarcinomas,Liver and intrahepatic bile ducts,Not Reported,Stage I,Not Reported,male,white,Alive,33e340f9-a97a-56eb-a3e6-aad831681cb4,Moffitt Cancer Center
438,TCGA-RC-A7S9-01A,Primary Tumor,Tumor,Adenomas and Adenocarcinomas,Liver and intrahepatic bile ducts,Not Reported,Stage I,Not Reported,female,asian,Alive,ae9dc463-76e6-5b63-9123-f080997fdf85,University of Utah

In [13]:
# Shows the count of unique classes per column across the whole dataset
unique_counts = clinical_lihc_pd_filtered.nunique()
print(unique_counts)

sample                                      439
sample_type.samples                           3
tissue_type.samples                           2
disease_type                                  1
primary_site                                  1
tumor_grade.diagnoses                         1
ajcc_pathologic_stage.diagnoses               9
alcohol_history.exposures                     1
gender.demographic                            2
race.demographic                              5
vital_status.demographic                      3
tissue_source_site_id.tissue_source_site     38
name.tissue_source_site                      38
dtype: int64

In [14]:
for col in clinical_lihc_pd_filtered.columns:
    print(f"--- {col} ---")
    print(clinical_lihc_pd_filtered[col].value_counts())
    print("\n")

--- sample ---
sample
TCGA-DD-A73C-01A    1
TCGA-DD-A115-11A    1
TCGA-BC-A216-11A    1
TCGA-KR-A7K8-01A    1
TCGA-DD-AAC8-01A    1
                   ..
TCGA-DD-AAD5-01A    1
TCGA-DD-A39X-01A    1
TCGA-DD-A39X-11A    1
TCGA-FV-A4ZQ-01A    1
TCGA-RC-A7S9-01A    1
Name: count, Length: 439, dtype: int64


--- sample_type.samples ---
sample_type.samples
Primary Tumor          377
Solid Tissue Normal     59
Recurrent Tumor          3
Name: count, dtype: int64


--- tissue_type.samples ---
tissue_type.samples
Tumor     380
Normal     59
Name: count, dtype: int64


--- disease_type ---
disease_type
Adenomas and Adenocarcinomas    439
Name: count, dtype: int64


--- primary_site ---
primary_site
Liver and intrahepatic bile ducts    439
Name: count, dtype: int64


--- tumor_grade.diagnoses ---
tumor_grade.diagnoses
Not Reported    439
Name: count, dtype: int64


--- ajcc_pathologic_stage.diagnoses ---
ajcc_pathologic_stage.diagnoses
Stage I       199
Stage II      100
Stage IIIA     74
Stage IIIB     10
Stage IIIC     10
Stage III       6
Stage IV        3
Stage IVB       2
Stage IVA       1
Name: count, dtype: int64


--- alcohol_history.exposures ---
alcohol_history.exposures
Not Reported    439
Name: count, dtype: int64


--- gender.demographic ---
gender.demographic
male      293
female    146
Name: count, dtype: int64


--- race.demographic ---
race.demographic
white                               230
asian                               170
black or african american            24
not reported                         13
american indian or alaska native      2
Name: count, dtype: int64


--- vital_status.demographic ---
vital_status.demographic
Alive           265
Dead            172
Not Reported      2
Name: count, dtype: int64


--- tissue_source_site_id.tissue_source_site ---
tissue_source_site_id.tissue_source_site
c2eb5c30-93cc-5a99-b9e4-f676e35ed7f8    185
addd7b04-91a3-5179-99a5-cbff20df6bb4     36
735fda57-1a46-5afd-a1c0-99af9115c0af     33
be652f28-50ec-5d4e-bc42-79a304ee03db     32
33e340f9-a97a-56eb-a3e6-aad831681cb4     20
98428b7d-30e7-5283-b22d-450c17717d09     16
8d5c4bc3-5ad6-5c07-8738-a6632e4d59d4     15
dbcb7cb8-b22c-5a78-9d41-b93e7eb08f05     10
ae9dc463-76e6-5b63-9123-f080997fdf85      9
2a8f962a-d2a8-5fb6-aea0-6bf694c0769c      8
9063dd32-2419-5b6e-a800-67ea5f1f71f4      7
86f2ecb2-6c8a-51da-943d-4acb6d72576d      5
04898289-8edf-590e-8640-35e36365de75      5
2b1c1097-fa63-5d15-b5d3-c54f5eacb9c8      5
33a38997-77be-52dc-b79d-890d8d4b792b      5
72165b47-b0b5-5107-b0be-b5a74bc3e249      4
29bb87f7-7e08-54b6-9bf8-b321a9926f80      4
f9ebb17f-fdca-5a0e-b026-dcb173867634      4
9a7a9c39-f289-5594-972a-ff9157a187f0      3
39c0854e-a35b-56ba-ae48-3d0f45b5c305      3
cf12df24-06a9-523f-ab6c-234ab95cf1c9      3
994ff94f-5d44-5de6-908b-dea33dca2a3d      3
0e691470-b18b-5803-9e4a-ee2cfbaae7b4      3
ef6a28c0-1733-5c00-be40-0ea911305be8      3
1ba22d72-8f0f-55c1-a40a-1d56ddb5f5a6      2
2deb19ef-f2aa-5861-87c8-f5c755f8800b      2
2e3c05db-a4a5-5563-9933-a10940cec98b      2
b521e8d8-2b93-5a14-9fd0-ece883fd1327      2
908d67b1-6836-521b-94a0-23d4ff8f2ccb      1
8d6f3ff9-3b72-5dfe-98b6-b9a65a51d5ce      1
8d6b695e-3dee-583e-9540-9c6d2435cfb5      1
de3a3fc3-2a44-5862-abc9-ab271401aba1      1
08ca7e8a-4c6f-5134-b202-078784e8e0e4      1
73d67bfc-0459-5e54-8bf1-ebcd1c12a4c7      1
426f3759-b687-5b34-98fc-7b6e44c9c540      1
73b91143-060e-5d8f-8183-b5dff41350b0      1
f9d27424-561d-5b8b-9351-bc1e1cb59caa      1
b7e5500b-b955-5cde-a867-d96d6a24bac9      1
Name: count, dtype: int64


--- name.tissue_source_site ---
name.tissue_source_site
Mayo Clinic - Rochester                         185
Alberta Health Services                          36
UNC                                              33
ILSBio                                           32
Moffitt Cancer Center                            20
International Genomics Consortium                16
Asterand                                         15
Christiana Healthcare                            10
University of Utah                                9
UCSF                                              8
Medical College of Wisconsin                      7
University of Pittsburgh                          5
University of Sao Paulo                           5
BLN - Baylor                                      5
Tayside Tissue Bank                               5
University Of Michigan                            4
University of Florida                             4
ABS - Lahey Clinic                                4
Proteogenex, Inc                                  3
Yale University                                   3
ABS - IUPUI                                       3
Cureline                                          3
St. Joseph's Medical Center-(MD)                  3
Hartford Hospital                                 3
Roswell Park                                      2
University of Kansas                              2
University of Minnesota                           2
Ontario Institute for Cancer Research (OICR)      2
Saint Mary's Health Care                          1
St. Joseph's Hospital Arizona                     1
Duke University                                   1
Fox Chase                                         1
University of California San Diego                1
Greenville Health System                          1
Montefiore Medical Center                         1
Emory University                                  1
Spectrum Health                                   1
Boston Medical Center                             1
Name: count, dtype: int64

In [15]:
clinical_lihc_pd_filtered = clinical_lihc_pd_filtered.drop(columns=["disease_type", "primary_site", "tumor_grade.diagnoses", "alcohol_history.exposures"])
clinical_lihc_pd_filtered

,sample,sample_type.samples,tissue_type.samples,ajcc_pathologic_stage.diagnoses,gender.demographic,race.demographic,vital_status.demographic,tissue_source_site_id.tissue_source_site,name.tissue_source_site
0,TCGA-DD-A73C-01A,Primary Tumor,Tumor,Stage IIIA,female,white,Alive,c2eb5c30-93cc-5a99-b9e4-f676e35ed7f8,Mayo Clinic - Rochester
1,TCGA-5C-AAPD-01A,Primary Tumor,Tumor,Stage II,male,asian,Alive,994ff94f-5d44-5de6-908b-dea33dca2a3d,Cureline
2,TCGA-ZS-A9CE-01A,Primary Tumor,Tumor,Stage II,female,white,Alive,33a38997-77be-52dc-b79d-890d8d4b792b,Tayside Tissue Bank
3,TCGA-HP-A5N0-01A,Primary Tumor,Tumor,NaN,female,not reported,Dead,b521e8d8-2b93-5a14-9fd0-ece883fd1327,Ontario Institute for Cancer Research (OICR)
4,TCGA-DD-AAVQ-01A,Primary Tumor,Tumor,Stage I,male,asian,Alive,c2eb5c30-93cc-5a99-b9e4-f676e35ed7f8,Mayo Clinic - Rochester
...,...,...,...,...,...,...,...,...,...
434,TCGA-DD-A73E-01A,Primary Tumor,Tumor,Stage I,male,white,Alive,c2eb5c30-93cc-5a99-b9e4-f676e35ed7f8,Mayo Clinic - Rochester
435,TCGA-CC-A7IH-01A,Primary Tumor,Tumor,Stage IIIA,male,asian,Alive,be652f28-50ec-5d4e-bc42-79a304ee03db,ILSBio
436,TCGA-BW-A5NO-01A,Primary Tumor,Tumor,Stage IIIA,male,black or african american,Alive,0e691470-b18b-5803-9e4a-ee2cfbaae7b4,St. Joseph's Medical Center-(MD)
437,TCGA-2Y-A9H9-01A,Primary Tumor,Tumor,Stage I,male,white,Alive,33e340f9-a97a-56eb-a3e6-aad831681cb4,Moffitt Cancer Center
438,TCGA-RC-A7S9-01A,Primary Tumor,Tumor,Stage I,female,asian,Alive,ae9dc463-76e6-5b63-9123-f080997fdf85,University of Utah

In [16]:
clinical_lihc_pd_filtered.isna().sum()

sample                                       0
sample_type.samples                          0
tissue_type.samples                          0
ajcc_pathologic_stage.diagnoses             34
gender.demographic                           0
race.demographic                             0
vital_status.demographic                     0
tissue_source_site_id.tissue_source_site     0
name.tissue_source_site                      0
dtype: int64

In [17]:
clinical_lihc_pd_filtered['ajcc_pathologic_stage.diagnoses'] = clinical_lihc_pd_filtered['ajcc_pathologic_stage.diagnoses'].fillna('Unknown')
clinical_lihc_pd_filtered.isna().sum()

sample                                      0
sample_type.samples                         0
tissue_type.samples                         0
ajcc_pathologic_stage.diagnoses             0
gender.demographic                          0
race.demographic                            0
vital_status.demographic                    0
tissue_source_site_id.tissue_source_site    0
name.tissue_source_site                     0
dtype: int64

In [18]:
clinical_lihc_pd_filtered_all = clinical_lihc_pd_filtered.copy()
clinical_lihc_pd_filtered_tumor = clinical_lihc_pd_filtered[clinical_lihc_pd_filtered['sample_type.samples'] == 'Primary Tumor']

In [19]:
clinical_lihc_pd_filtered_tumor

,sample,sample_type.samples,tissue_type.samples,ajcc_pathologic_stage.diagnoses,gender.demographic,race.demographic,vital_status.demographic,tissue_source_site_id.tissue_source_site,name.tissue_source_site
0,TCGA-DD-A73C-01A,Primary Tumor,Tumor,Stage IIIA,female,white,Alive,c2eb5c30-93cc-5a99-b9e4-f676e35ed7f8,Mayo Clinic - Rochester
1,TCGA-5C-AAPD-01A,Primary Tumor,Tumor,Stage II,male,asian,Alive,994ff94f-5d44-5de6-908b-dea33dca2a3d,Cureline
2,TCGA-ZS-A9CE-01A,Primary Tumor,Tumor,Stage II,female,white,Alive,33a38997-77be-52dc-b79d-890d8d4b792b,Tayside Tissue Bank
3,TCGA-HP-A5N0-01A,Primary Tumor,Tumor,Unknown,female,not reported,Dead,b521e8d8-2b93-5a14-9fd0-ece883fd1327,Ontario Institute for Cancer Research (OICR)
4,TCGA-DD-AAVQ-01A,Primary Tumor,Tumor,Stage I,male,asian,Alive,c2eb5c30-93cc-5a99-b9e4-f676e35ed7f8,Mayo Clinic - Rochester
...,...,...,...,...,...,...,...,...,...
434,TCGA-DD-A73E-01A,Primary Tumor,Tumor,Stage I,male,white,Alive,c2eb5c30-93cc-5a99-b9e4-f676e35ed7f8,Mayo Clinic - Rochester
435,TCGA-CC-A7IH-01A,Primary Tumor,Tumor,Stage IIIA,male,asian,Alive,be652f28-50ec-5d4e-bc42-79a304ee03db,ILSBio
436,TCGA-BW-A5NO-01A,Primary Tumor,Tumor,Stage IIIA,male,black or african american,Alive,0e691470-b18b-5803-9e4a-ee2cfbaae7b4,St. Joseph's Medical Center-(MD)
437,TCGA-2Y-A9H9-01A,Primary Tumor,Tumor,Stage I,male,white,Alive,33e340f9-a97a-56eb-a3e6-aad831681cb4,Moffitt Cancer Center
438,TCGA-RC-A7S9-01A,Primary Tumor,Tumor,Stage I,female,asian,Alive,ae9dc463-76e6-5b63-9123-f080997fdf85,University of Utah

In [20]:
# 1. Extract the valid sample IDs from your clinical dataframe into a list
valid_tumor_samples = clinical_lihc_pd_filtered_tumor['sample'].tolist()
valid_all_samples = clinical_lihc_pd_filtered_all['sample'].tolist() # Assuming you have this too

# 2. Filter the methylation dataframe keeping only rows where the Index matches the list
methylation_lihc_pd_tumor = methylation_lihc_pd[methylation_lihc_pd.index.isin(valid_tumor_samples)]
methylation_lihc_pd_all = methylation_lihc_pd[methylation_lihc_pd.index.isin(valid_all_samples)]

In [21]:
methylation_lihc_pd_all

Composite Element REF,cg00000108,cg00000109,cg00000236,cg00000292,cg00000321,cg00000363,cg00000622,cg00000658,cg00000714,cg00000721,...,ctl_70664314,ctl_70700334,ctl_71670310,ctl_71678368,ctl_71718498,ctl_72748406,ctl_73635489,ctl_73784382,ctl_73794434,ctl_74666473
TCGA-DD-A73D-01A,0.117137,0.924546,0.943050,0.657382,0.076094,0.851907,0.014520,0.796828,0.408849,0.959089,...,0.016190,0.058347,0.963264,0.056226,0.109904,0.098351,0.066046,0.939816,0.955241,0.961276
TCGA-G3-A5SK-01A,0.428748,0.908687,0.918806,0.676207,0.198359,0.751913,0.014256,0.840600,0.167963,0.957603,...,0.017244,0.096494,0.956808,0.075496,0.095065,0.097984,0.088078,0.931223,0.946813,0.957117
TCGA-DD-A1EL-11A,0.590056,0.962914,0.853267,0.811190,0.254828,0.615154,0.013704,0.903124,0.248404,0.961450,...,0.048371,0.050236,0.957189,0.051330,0.178029,0.067013,0.052013,0.942271,0.952217,0.967854
TCGA-DD-AAD8-01A,0.164315,0.802248,0.855616,0.719729,0.121652,0.642324,0.011543,0.845569,0.113078,0.937181,...,0.026267,0.101110,0.912187,0.114697,0.111062,0.117661,0.110835,0.893607,0.792508,0.960780
TCGA-WX-AA47-01A,0.259369,0.913790,0.931874,0.792509,0.083664,0.800295,0.015096,0.822098,0.109717,0.947942,...,0.022311,0.105520,0.955789,0.060052,0.101830,0.100906,0.081402,0.934609,0.938779,0.969138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-RC-A7S9-01A,0.727903,0.917399,0.879191,0.498206,0.248408,0.859052,0.012922,0.864288,0.097928,0.929429,...,0.017357,0.062147,0.960526,0.056585,0.099479,0.102135,0.066599,0.934101,0.948080,0.963495
TCGA-CC-A9FS-01A,0.967289,0.891528,0.860259,0.945034,0.676335,0.754555,0.013039,0.840799,0.107899,0.933557,...,0.026578,0.091685,0.919480,0.098662,0.094480,0.110258,0.170863,0.852174,0.930500,0.967402
TCGA-DD-AAEB-01A,0.321233,0.869649,0.865454,0.610651,0.127981,0.860820,0.011846,0.846064,0.184822,0.273931,...,0.022636,0.091522,0.937423,0.093921,0.129181,0.117661,0.078684,0.896254,0.891230,0.959803
TCGA-EP-A3RK-01A,0.731066,0.876023,0.951141,0.853662,0.243828,0.721904,0.011956,0.845202,0.172222,0.957277,...,0.015384,0.065589,0.961302,0.058295,0.103602,0.091236,0.063071,0.949478,0.962490,0.960636
TCGA-GJ-A3OU-01A,0.720276,0.917732,0.907275,0.848464,0.351756,0.572167,0.016130,0.828588,0.206280,0.950362,...,0.054325,0.090232,0.946123,0.054699,0.194749,0.140927,0.065614,0.951649,0.959182,0.968255

In [22]:
methylation_lihc_pd_tumor

Composite Element REF,cg00000108,cg00000109,cg00000236,cg00000292,cg00000321,cg00000363,cg00000622,cg00000658,cg00000714,cg00000721,...,ctl_70664314,ctl_70700334,ctl_71670310,ctl_71678368,ctl_71718498,ctl_72748406,ctl_73635489,ctl_73784382,ctl_73794434,ctl_74666473
TCGA-DD-A73D-01A,0.117137,0.924546,0.943050,0.657382,0.076094,0.851907,0.014520,0.796828,0.408849,0.959089,...,0.016190,0.058347,0.963264,0.056226,0.109904,0.098351,0.066046,0.939816,0.955241,0.961276
TCGA-G3-A5SK-01A,0.428748,0.908687,0.918806,0.676207,0.198359,0.751913,0.014256,0.840600,0.167963,0.957603,...,0.017244,0.096494,0.956808,0.075496,0.095065,0.097984,0.088078,0.931223,0.946813,0.957117
TCGA-DD-AAD8-01A,0.164315,0.802248,0.855616,0.719729,0.121652,0.642324,0.011543,0.845569,0.113078,0.937181,...,0.026267,0.101110,0.912187,0.114697,0.111062,0.117661,0.110835,0.893607,0.792508,0.960780
TCGA-WX-AA47-01A,0.259369,0.913790,0.931874,0.792509,0.083664,0.800295,0.015096,0.822098,0.109717,0.947942,...,0.022311,0.105520,0.955789,0.060052,0.101830,0.100906,0.081402,0.934609,0.938779,0.969138
TCGA-DD-A1EL-01A,0.619059,0.844312,0.866817,0.527882,0.198699,0.709242,0.015173,0.929196,0.135481,0.780788,...,0.072262,0.080303,0.943996,0.051412,0.213589,0.052199,0.085660,0.936370,0.940137,0.959429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-RC-A7S9-01A,0.727903,0.917399,0.879191,0.498206,0.248408,0.859052,0.012922,0.864288,0.097928,0.929429,...,0.017357,0.062147,0.960526,0.056585,0.099479,0.102135,0.066599,0.934101,0.948080,0.963495
TCGA-CC-A9FS-01A,0.967289,0.891528,0.860259,0.945034,0.676335,0.754555,0.013039,0.840799,0.107899,0.933557,...,0.026578,0.091685,0.919480,0.098662,0.094480,0.110258,0.170863,0.852174,0.930500,0.967402
TCGA-DD-AAEB-01A,0.321233,0.869649,0.865454,0.610651,0.127981,0.860820,0.011846,0.846064,0.184822,0.273931,...,0.022636,0.091522,0.937423,0.093921,0.129181,0.117661,0.078684,0.896254,0.891230,0.959803
TCGA-EP-A3RK-01A,0.731066,0.876023,0.951141,0.853662,0.243828,0.721904,0.011956,0.845202,0.172222,0.957277,...,0.015384,0.065589,0.961302,0.058295,0.103602,0.091236,0.063071,0.949478,0.962490,0.960636
TCGA-GJ-A3OU-01A,0.720276,0.917732,0.907275,0.848464,0.351756,0.572167,0.016130,0.828588,0.206280,0.950362,...,0.054325,0.090232,0.946123,0.054699,0.194749,0.140927,0.065614,0.951649,0.959182,0.968255

In [23]:
#save the filtered dataframes for later use
methylation_lihc_pd_all.to_csv('../data/processed/methylation_lihc_pd_all.csv')
methylation_lihc_pd_tumor.to_csv('../data/processed/methylation_lihc_pd_tumor.csv')
clinical_lihc_pd_filtered_all.to_csv('../data/processed/clinical_lihc_pd_filtered_all.csv')
clinical_lihc_pd_filtered_tumor.to_csv('../data/processed/clinical_lihc_pd_filtered_tumor.csv')