In [1]:
import pandas as pd
import os

# Define file paths
csv_file_path = '../data/processed/clinical_hnsc_all.csv'
txt_file_path = '../data/raw/Subtype_Immune_Model_Based.txt'
output_dir = '../data/processed'
output_file_path = os.path.join(output_dir, 'clinical_hnsc_all_sb.csv')

# 1. Load the data
df_csv = pd.read_csv(csv_file_path)
df_txt = pd.read_csv(txt_file_path, sep='\t')

# 2. Create a matching key in the CSV DataFrame
# We take the first 15 characters to remove the trailing 'A', 'B', etc.
df_csv['sample_match'] = df_csv['sample'].str[:15]

# 3. Merge the DataFrames
# We use left_on and right_on since the matching columns have different names now
merged_df = pd.merge(
    df_csv, 
    df_txt[['sample', 'Subtype_Immune_Model_Based']], 
    left_on='sample_match', 
    right_on='sample', 
    how='left',
    suffixes=('', '_txt') # Prevents the original 'sample' column from being renamed to 'sample_x'
)

# 4. Clean up columns
# Drop the temporary matching column and the extra 'sample' column from the txt file
merged_df = merged_df.drop(columns=['sample_match', 'sample_txt'])

# Rename the new feature column
merged_df = merged_df.rename(columns={'Subtype_Immune_Model_Based': 'immune_subtypes'})

# 5. Save the result
os.makedirs(output_dir, exist_ok=True)
#merged_df.to_csv(output_file_path, index=False)

#print(f"File successfully saved to: {output_file_path}")

In [2]:
merged_df

,Unnamed: 0,sample,tissue_type.samples,alcohol_history.exposures,immune_subtypes
0,0,TCGA-BB-4227-01A,Tumor,Yes,Wound Healing (Immune C1)
1,1,TCGA-CR-6478-01A,Tumor,Yes,IFN-gamma Dominant (Immune C2)
2,2,TCGA-BB-4228-01A,Tumor,Yes,Wound Healing (Immune C1)
3,3,TCGA-BA-4075-01A,Tumor,Yes,NaN
4,4,TCGA-CX-7082-01A,Tumor,Yes,NaN
...,...,...,...,...,...
575,598,TCGA-CV-7242-01A,Tumor,Yes,IFN-gamma Dominant (Immune C2)
576,600,TCGA-TN-A7HL-01A,Tumor,Yes,IFN-gamma Dominant (Immune C2)
577,601,TCGA-CV-A6JZ-01A,Tumor,Yes,IFN-gamma Dominant (Immune C2)
578,602,TCGA-CV-5444-11A,Normal,Yes,NaN
579,603,TCGA-CV-5444-01A,Tumor,Yes,IFN-gamma Dominant (Immune C2)

In [3]:
# import pandas as pd
# import os

# # Define file paths
# csv_file_path = os.path.join('../data/processed', 'clinical_hnsc_all_sb.csv')
# tsv_file_path = '../data/raw/TCGASubtype.20170308.tsv'

# # 1. Load the data
# df_csv = merged_df # Assuming this is the DataFrame from the previous step
# df_tsv = pd.read_csv(tsv_file_path, sep='\t')

# # 2. Select only the necessary columns from the TSV
# columns_to_add = [
#     'sampleID', # Keep this for the merge
#     'Subtype_CNA',
#     'Subtype_DNAmeth',
#     'Subtype_Integrative',
#     'Subtype_Selected',
#     'Subtype_mRNA',
#     'Subtype_miRNA',
#     'Subtype_other',
#     'Subtype_protein'
# ]
# df_tsv_subset = df_tsv[columns_to_add]

# # 3. Create a matching key in the CSV DataFrame
# # Extract the first 15 characters (e.g., TCGA-HZ-7918-01) to match the TSV format
# df_csv['sample_match'] = df_csv['sample'].str[:15]

# # 4. Merge the DataFrames
# merged_df = pd.merge(
#     df_csv, 
#     df_tsv_subset, 
#     left_on='sample_match', 
#     right_on='sampleID', 
#     how='left'
# )
# merged_df
# # 5. Clean up columns
# # Drop the temporary 'sample_match' and the redundant 'sampleID' from the TSV

In [4]:
#merged_df = merged_df.drop(columns=['sample_match', 'sampleID', 'Unnamed: 0'])
merged_df = merged_df.drop(columns=['Unnamed: 0'])

# 6. Save the result, overwriting the existing CSV file as requested
merged_df.to_csv(csv_file_path, index=False)

print(f"File successfully updated and saved to: {csv_file_path}")

File successfully updated and saved to: ../data/processed/clinical_hnsc_all.csv

In [5]:
merged_df

,sample,tissue_type.samples,alcohol_history.exposures,immune_subtypes
0,TCGA-BB-4227-01A,Tumor,Yes,Wound Healing (Immune C1)
1,TCGA-CR-6478-01A,Tumor,Yes,IFN-gamma Dominant (Immune C2)
2,TCGA-BB-4228-01A,Tumor,Yes,Wound Healing (Immune C1)
3,TCGA-BA-4075-01A,Tumor,Yes,NaN
4,TCGA-CX-7082-01A,Tumor,Yes,NaN
...,...,...,...,...
575,TCGA-CV-7242-01A,Tumor,Yes,IFN-gamma Dominant (Immune C2)
576,TCGA-TN-A7HL-01A,Tumor,Yes,IFN-gamma Dominant (Immune C2)
577,TCGA-CV-A6JZ-01A,Tumor,Yes,IFN-gamma Dominant (Immune C2)
578,TCGA-CV-5444-11A,Normal,Yes,NaN
579,TCGA-CV-5444-01A,Tumor,Yes,IFN-gamma Dominant (Immune C2)